### ISSUE TITLE
'indnames' referenced before assigment

### ISSUE THREAD

**Issue by jkreinz** [isaacovercast/easySFS#10]
I keep running into an error message about indnames being unassigned when trying to run the first step of the program. Below is the command and error message.

` python2 easySFS.py -i ~/software/snpEff/ont_ill_missingfilt.syn.ann.vcf -p pop.file --preview`
Processing 3 populations - ['pop1', 'pop2', 'pop3']
Traceback (most recent call last):
  File "easySFS.py", line 536, in <module>
    main()
  File "easySFS.py", line 489, in main
    indnames = get_inds_from_input(args.vcf_name, args.verbose)
  File "easySFS.py", line 311, in get_inds_from_input
    return indnames
UnboundLocalError: local variable 'indnames' referenced before assignment

Thanks for the script and your help!

**Comment by isaacovercast** [comment]
Hey there,
This would only happen if the vcf file you're reading from is malformed, or at least formatted in a way different than the script expects. easySFS is looking for the line in the vcf that starts with `#CHROM`, then it parses it for sample names as all columns that follow the `FORMAT` column. What does the header of your vcf file look like?

**Comment by isaacovercast** [comment]
Closing since this seems like a dead issue.
