### ISSUE TITLE
The VCF file passed does not have rad locus info in the Chrom field.

### ISSUE THREAD

**Issue by MrLocuace** [isaacovercast/easySFS#11]
Hello, I have a VCF file from 1 population with this format:

##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##filedate=20160106
##source="beagle.jar (r1399)"
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated Allele Frequencies">
##INFO=<ID=AR2,Number=1,Type=Float,Description="Allelic R-Squared: estimated correlation between most probable ALT dose and true ALT dose">
##INFO=<ID=DR2,Number=1,Type=Float,Description="Dosage R-Squared: estimated correlation between estimated ALT dose [P(RA) + 2*P(AA)] and true ALT dose">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=21>
##bcftools_annotateVersion=1.9+htslib-1.9
##bcftools_annotateCommand=annotate -x FORMAT/DS,FORMAT/GP -o /results/mydata; Date=Mon Aug 13 19:22:34 2018
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT    sample1    sample2
21	14665973	rs2742182	C	T	.	PASS	AR2=1;DR2=1;AF=0.613	GT    1|1	0|1

When I run:

./easySFS.py -i /results/data.vcf \
             -p /results/pop_data.txt -a --proj 12

I get some messages like this one:

RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import lib, groupby as libgroupby, Timestamp, NaT, iNaT
 
and 

Processing 1 populations - ['CHL']
  Sampling one snp per locus

    VCF file uses non-standard Chrom/pos information.
    We assume that Chrom indicates RAD loci and pos indicates snps within each locus 
    The VCF file passed does not have rad locus info in the Chrom field.

The same happens when I run the example provided by you.

It seems that my VCF format is not RAD-like (I cannot find what is a RAD-like VCF format). Or perhaps this package doesn't work with phased data?. Any suggestion will be highly welcome. Thank you very much

**Comment by isaacovercast** [comment]
Hello, sorry for the delayed response, I was at the Evoloution meeting. easySFS should handle phased data fine. Also, when you say you get this behavior from the example data, can you show me the exact commands you're running? The example data still works fine for me.

The behavior you are seeing here is related to the number of CHROM blocks found in your vcf file. easySFS is targeted toward RAD-like vcf output, so I assume that each rad locus is described by one CHROM value. In this way, as is typical, by default I sample one snp per RAD locus. If you want to use all snps in the data for calculating the SFS then you can use the `-a` flag and it will use all snps, not just one per CHROM block.

From the look of your data it appears to be whole-genome:

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT sample1 sample2
21	14665973	rs2742182	C	T	.	PASS	AR2=1;DR2=1;AF=0.613	GT 1|1	0|1

If all your snps are assigned to CHROM 21, then this will produce this behavior. Including the `-a` flag will prevent the random subsampling, and _should_ just work, but in this case you'd be ignoring linkage among sites (which may or may not be a problem). One strategy you could use would be to use vcftools to randomly sample one snp per 1kb or 10kb or whatever, and then use easySFS with the `-a` flag, as you will have effectively handled linkage already at this point. Hope that helps!

**Comment by MrLocuace** [comment]
Thank you very much, Isaac. I solved the problem. It was a formatting mistake.

All the best
