### ISSUE TITLE
unfolded SFS

### ISSUE THREAD

**Issue by BegonaMartinez** [isaacovercast/easySFS#12]
Hi, 

I am using easySFS to convert my vcf into SFS (thanks a lot for this tool). I need the SFS in fastsimcoal format. I have a reference so in my vcf I have 0 for ancestral and 1 for derived, for two pops, and I want to obtain the unfolded SFS. The files I obtain have the name myProjectname_jointMAFpop0_1.obs and myProjectname_MSFS.obs (both similar but with different format). My doubt is whether these are unfolded or folded SFSs, given the notation "MAF" in one of the resultant files. 
Thanks a lot in advance. 

Best,

Begona

**Comment by isaacovercast** [comment]
Hi Begona,
As long as you used the `--unfolded` flag the SFS will be accurately unfolded, it's just the file name is wrong. You can rename these files from "MAF" to "DAF" and they will work fine in fsc. I will update easySFS script to name the files correctly.

**Comment by isaacovercast** [comment]
This is fixed now in the current repo. Files receive proper MAF/DAF filename based on the `--unfolded` flag.
