### ISSUE TITLE
Weird SFS

### ISSUE THREAD

**Issue by MrLocuace** [isaacovercast/easySFS#13]
Hello Isaac, I used easySFS to calculate the joint SFS of 3 populations (dadi format), but when plotting it I get very weird results (see attached). I followed all the steps and I don't know what went wrong. I would very grateful if I could send you the SFS and have some feedback from you.

Thank you very much,
Luc

![sfs](https://user-images.githubusercontent.com/20564007/46510582-42cc6400-c820-11e8-8cdc-836dcad40549.png)

**Comment by isaacovercast** [comment]
Hi Luc,
The sfs would be less helpful than the vcf and pops files it was generated from. It does look a little weird, but since I don't know anything about your system it's hard to say exactly _how_ weird ;p Did you look at the individual sfs per population, and the pairwise joint sfs? Did they still look "weird"? What do you expect these to look like, give your knowledge of the system?

**Comment by MrLocuace** [comment]
Thank you Isaac, I will check my SFS and VCF files

**Comment by MrLocuace** [comment]
Hi Isaac, here is an example of the SFS of one population:

78 folded "pop1"
121337.4487179487 21775.98717948806 7003.064102564444 2776.500000000187 1228.935897435878 685.2948717948932 373.2051282051517 241.9230769230845 137.9871794871773 101.3205128205169 52.5256410256432 46.88461538461782 20.75641025641147 20.96153846153883 9.743589743590213 6.66666666666694 2.756410256410276 10.50000000000029 13.97435897436004 9.358974358974571 5.205128205128482 0.5641025641025927 1.730769230769268 0.7051282051282391 0 0 0 0 0 0 0 0 1.269230769230842 1.730769230769365 0 0 0 0.487179487179517 0.5128205128205431 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

I don't know why the data was not produced in the format of your example:

Pop1
(2, 45.0)   (3, 59.0)   (4, 58.0)   (5, 49.0)   (6, 41.0) ...

I also don't know why it folded the SFS. These are the commands I used:

./easySFS.py \
-i my.vcf \
-p pop_file.txt \
-a --proj 389,77,389 \
-o out_sfs

Do you have any sugesstion?. Thanks very much

**Comment by isaacovercast** [comment]
This sfs looks fine to me. How does it look weird? 

How many samples do you have per population?

The format you seem to be expecting there is the output of the `--preview` command, which you are not running. If you want to see the preview results you need to use the `--preview` flag.

The sfs was folded because that is the default, if you want unfolded you need to specify that with the `--unfolded` flag.

**Comment by MrLocuace** [comment]
Hi Isaac, thank you for your response.  I have 200, 39 and 200 samples. You are right, I misunderstood the output of the --preview command with the --o command. The --unfolded/unfolded flag is not described in the readme or in the description of the script, that's why I did not notice it. Thanks again

**Comment by MrLocuace** [comment]
Hello Isaac, never mind !. 

The data produced with the "unfolded" flag makes more sense for me. Since you created this script for dadi and fastsimcoal, I'd like to ask you a question. I am not sure if you can advice me though. I am running some parameter optimizations in dadi and I get this warning:

WARNING:Inference:Model is < 0 where data is not masked.
WARNING:Inference:Number of affected entries is 4263996. Sum of data in those entries is 749.832:

I was wondering whether this could be related to the masking parameters you set up in easySFS.py for producing the joint unfolded SFS or the individual SFSs.

These are some entries of the joint SFS of 3 populations:

390 78 390 unfolded "pop1" "pop2" "pop3"
1724.913685159906 8469.779844575871 3737.432110791671.....

Thanks again,
Luc

**Comment by isaacovercast** [comment]
Hey Luc,
Glad its working for you now. I've never seen this dadi error before, so I'm not exactly sure what's going on. If you find that it _is_ a problem with the format of the SFS please let me know so I can fix the script.
-isaac

**Comment by MrLocuace** [comment]
OK, thank you Isaac !

**Comment by MrLocuace** [comment]
By the way, when I load the SFS produced by easySFS in dadi I get this warning:

./anaconda2/lib/python2.7/site-packages/dadi-1.7.0-py2.7-linux-x86_64.egg/dadi/Spectrum_mod.py:405: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

Not sure whether it's related to the easySFS output.
