### ISSUE TITLE
Cite script?

### ISSUE THREAD

**Issue by MrLocuace** [isaacovercast/easySFS#14]
Hello Isaac,
how do you want we acknowledge your script when using it for a publication?
Best,
Luc

**Comment by isaacovercast** [comment]
Hi Luc,
That would be great! Thanks. People have done this before and they normally just cite the github repo:

https://github.com/isaacovercast/easySFS

Thanks!
-isaac

**Comment by MrLocuace** [comment]
OK ! Thank you !
