### ISSUE TITLE
intersecting population set and vcf sample set

### ISSUE THREAD

**Issue by ab08028** [isaacovercast/easySFS#15]
Hi Isaac -- thanks for making such a useful wrapper for carrying out projections! I'm finding it really helpful. 

I ran into a minor issue, and I think might have a solution (apologies if I'm off base here). I had some individuals in my population file that weren't in the vcf and vice-versa, which should have been removed by your check_inputs function, but instead the entire population that contained the individuals was getting eliminated. I think I may have found where this is happening:

during the check_inputs function:
```
        for k,v in pops.items():
            for ind in pop_set.difference(vcf_set):
                if ind in v:
                    pops[k] = v.remove(ind) 
```
v.remove(ind) just removes the individual from v, but it doesn't return anything, so pops[k] was actually getting set to None.
I tried the following as an alternative, and it appears to be working as expected:
```
        for k,v in pops.items():
            for ind in pop_set.difference(vcf_set):
                if ind in v:
                    v.remove(ind) # doesn't return anything, just removes the entry from v 
                    pops[k] = v # then you set this to the new v in the subsequent step
```
Does that make sense as fix? I may have missed something along the way or it might be a python 2/3 issue... (I'm using python 2.7)

Thanks again!
~ Annabel

**Comment by isaacovercast** [comment]
Haha! Wow, I guess I didn't test that part of the script very well. Thanks for noticing, and your fix looks great. I added it to the repo. Thanks! Glad you like the script.

**Comment by ab08028** [comment]
Excellent! Cheers,
~ A  :)
