### ISSUE TITLE
easySFS outfile.write error

### ISSUE THREAD

**Issue by weniweni7** [isaacovercast/easySFS#16]
hi 
can anyone help

i use easySFS to create sfs file to fastimcoal2 then get the error like figure
when i type python3 ../../easySFS.py  -i wcs_1200.vcf -p wcs_pops.txt --preview -a , easySFS.py can show me the preview
but when i type  python3 ../../easySFS.py  -i wcs_1200.vcf -p wcs_pops.txt --proj 7,7 -a , is get some errors like below, i don't know how to fix it , can someone helps 
thanks for any helps

Traceback (most recent call last):
File "../../easySFS.py", line 646, in <module>
 main()
File "../../easySFS.py", line 624, in main
dadi_oneD_sfs_per_pop(dd, pops, proj=proj, unfold=args.unfolded, outdir=outdir, prefix=prefix, dtype=args.dtype)
File "../../easySFS.py", line 76, in dadi_oneD_sfs_per_pop
outfile.write("\t".join(["d0_"+str(x) for x in xrange(proj[i]+1)]) + "\n")
NameError: name 'xrange' is not defined

**Comment by isaacovercast** [comment]
Use python2. This is an easy problem to [google for yourself in the future.](https://www.google.com/search?q=name+%27xrange%27+is+not+defined&oq=name+%27xrange%27+is+not+defined&aqs=chrome..69i57j69i64.1155j0j7&sourceid=chrome&ie=UTF-8)

**Comment by weniweni7** [comment]
thanks Isaac Overcast



Isaac Overcast <notifications@github.com> 於 2019年3月29日 週五 下午9:41寫道：

**Comment by weniweni7** [comment]
hello Isaac
I am sorry to bother you again
when i install python2 in our server with nonroot user always some
import module error, it my problem
can i use python3 and change the xrange to range when i use easysfs
Is this going to be a problem for sfs transverses?
thanks for your advises

best
weni

Isaac Overcast <notifications@github.com> 於 2019年3月29日 週五 下午9:41寫道：

**Comment by isaacovercast** [comment]
Hello weni,
Python3 won't work because of the dadi dependency, and dadi is definitely
not python3 compliant. Did you try installing miniconda and installling
easySFS in a conda environment. This really should work 100% of the time.
Shouldn't matter whether you're root or not.
-isaac

**Comment by weniweni7** [comment]
thanks isaac
I will try the advise thank you so much

another question if i can use python3  run dadi/tests/run_tests.py when get
ok, whether indicate python3 can run dadi also?
if i just want to trans population snp calling .vcf to .sfs for
fastsimicol2 and when i change xrange to range in easysfs.py. easysfs can
get me for dadi and fastsimicol2 .sfs files whether mean it work ?
if work I want to confirm the  numbers of sfs calculation it ok for use
this way ?
but your right when use python3 to run dadi files of some.py if relate to
xrange i will get error too
sorry too many questions

best
weni



Isaac Overcast <notifications@github.com> 於 2019年4月8日 週一 下午11:25寫道：

**Comment by isaacovercast** [comment]
I mean if you change xrange to range and it works, then i'd believe the results are okay. If it works i'm sure it's fine, i just didn't think it would work and I've never tried it.

**Comment by weniweni7** [comment]
ok, very thanks for reply
best



Isaac Overcast <notifications@github.com> 於 2019年4月9日 週二 下午11:06寫道：
