### ISSUE TITLE
ImportError: No module named copyreg

### ISSUE THREAD

**Issue by angelesdecara** [isaacovercast/easySFS#17]
Hi,
I'm trying to calculate the SFS for 6 populations. I've obtained the same error in two computers running ubuntu. If I run ./easySFS.py or ./easySFS.py -i example_files/wcs_1200.vcf -p example_files/wcs_pops.txt -a --preview , I get this message:

Traceback (most recent call last):
  File "./easySFS.py", line 18, in <module>
    import dadi
  File "build/bdist.linux-x86_64/egg/dadi/__init__.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/dadi/Demographics1D.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/dadi/Spectrum_mod.py", line 2129, in <module>
ImportError: No module named copyreg

It doesn't seem related to easySFS.py per se, but just in case you can help, as I obtain this very error in two computers.
Thanks!

**Comment by isaacovercast** [comment]
copyreg is python3, but dadi (and therefore easySFS) is python2 only at
this point. Looks like a python version issue. Be sure you're running in a
python 2.7 environment.

**Comment by angelesdecara** [comment]
Thanks! How do I know which python environment I'm running on? sorry if it's a daft question...

**Comment by isaacovercast** [comment]
`python -V`

**Comment by isaacovercast** [comment]
easySFS supports python3 now, so this shouldn't be a problem in the future.
