### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by angelesdecara** [isaacovercast/easySFS#18]
Hi,

My sys adm has installed easySFS on the cluster, but... while it runs no problem with --preview, this is the result of
./easySFS.py -i example_files/wcs_1200.vcf -p example_files/wcs_pops.txt -a --proj 12,20

./easySFS.py:457: DeprecationWarning: 'U' mode is deprecated
  with open(pops_file, 'rU') as popsfile:
Processing 2 populations - odict_keys(['nuttalli', 'pugetensis'])
./easySFS.py:389: DeprecationWarning: 'U' mode is deprecated
  with ofunc(vcf_name, 'rU') as infile:
Doing 1D sfs - nuttalli
Traceback (most recent call last):
  File "./easySFS.py", line 646, in <module>
    main()
  File "./easySFS.py", line 624, in main
    dadi_oneD_sfs_per_pop(dd, pops, proj=proj, unfold=args.unfolded, outdir=outdir, prefix=prefix, dtype=args.dtype)
  File "./easySFS.py", line 76, in dadi_oneD_sfs_per_pop
    outfile.write("\t".join(["d0_"+str(x) for x in xrange(proj[i]+1)]) + "\n")
NameError: name 'xrange' is not defined

Many thanks for all your help!

**Comment by isaacovercast** [comment]
Yep, python3 does not have xrange, so you'll need to install easySFS in a
python2 environment. I've been meaning to update easysfs to python3, but
havne't gotten around to it yet, sorry for the trouble.

**Comment by isaacovercast** [comment]
This is fixed now if you use python 3 and the new install instructions (pulling dadi from the bioconda channel).
