### ISSUE TITLE
About the --proj parameter in easySFS 

### ISSUE THREAD

**Issue by Yun-HongWu** [isaacovercast/easySFS#20]
Hello Isaac, in my data set(whole-genome VCF files), it includes 5 populations and the samples/individuals of each population are 5,6,2,37and 57. So could you give some advice to set the --proj when i run easySFS? Should i set --proj 10,12,4,74,114? Thank you in advance.

**Comment by isaacovercast** [comment]
Hello,
The `--proj` values should be set to maximize the number of segregating sites, which you can evaluate with the --preview flag. The values for `--proj` that you suggest are valid, and these will retain only sites that are present in all samples.

**Comment by Yun-HongWu** [comment]
Hi Isaac, Thanks for your reply. I have follown your suggestion to process my data set. First i run the --preview flag to evaluate my data set. and i have got the result :
It seems that for my 5 populations the best sample size used in --proj flag are 4,70,12,10 and 114. So i rerun the easySFS.py to infer the SFS results. When i checked my result files i found for the "XXX__jointDAFpop4_1.obs" file ,there are too many "0" values in the joint SFS matrix, it looks like :
So did i miss some improtant things during my data processing ? And whether this pattern is normal ?  Thanks again ! Looking forward your reply.
Best Wishes.

At 2019-09-26 23:37:07, "Isaac Overcast" <notifications@github.com> wrote:


Hello,
The --proj values should be set to maximize the number of segregating sites, which you can evaluate with the --preview flag. The values for --proj that you suggest are valid, and these will retain only sites that are present in all samples.

**Comment by Yun-HongWu** [comment]
Hi Isaac, Thanks for your reply. I have follown your suggestion to process my data set. First i run the --preview flag to evaluate my data set. and i have got the result :


Ravu
(2, 13808.0)    (3, 20711.0)    (4, 24254.0)




Rbie
(2, 7937.0)     (3, 11906.0)    (4, 14376.0)    (5, 16097.0)    (6, 17383.0)    (7, 18393.0)    (8, 19213.0)    (9, 19898.0)    (10, 20481.0)   (11, 20987.0)   (12, 21430.0)   (13, 21823.0)(14, 22174.0)   (15, 22492.0)   (16, 22780.0)   (17, 23044.0)   (18, 23286.0)   (19, 23510.0)   (20, 23717.0)   (21, 23910.0)   (22, 24090.0)   (23, 24259.0)   (24, 24417.0)   (25, 24567.0)(26, 24708.0)   (27, 24842.0)   (28, 24969.0)   (29, 25089.0)   (30, 25204.0)   (31, 25314.0)   (32, 25418.0)   (33, 25519.0)   (34, 25615.0)   (35, 25707.0)   (36, 25796.0)   (37, 25881.0)(38, 25963.0)   (39, 26042.0)   (40, 26119.0)   (41, 26193.0)   (42, 26264.0)   (43, 26334.0)   (44, 26401.0)   (45, 26466.0)   (46, 26529.0)   (47, 26591.0)   (48, 26650.0)   (49, 26708.0)(50, 26765.0)   (51, 26820.0)   (52, 26874.0)   (53, 26926.0)   (54, 26977.0)   (55, 27027.0)   (56, 27076.0)   (57, 27123.0)   (58, 27170.0)   (59, 27216.0)   (60, 27260.0)   (61, 27304.0)(62, 27347.0)   (63, 27389.0)   (64, 27430.0)   (65, 27470.0)   (66, 27510.0)   (67, 27549.0)   (68, 27587.0)   (69, 27624.0)   (70, 27661.0)




Rstr
(2, 5610.0)     (3, 8415.0)     (4, 10373.0)    (5, 11907.0)    (6, 13198.0)    (7, 14333.0)    (8, 15363.0)    (9, 16315.0)    (10, 17209.0)   (11, 18056.0)   (12, 18866.0)




Rbre
(2, 15122.0)    (3, 22683.0)    (4, 27195.0)    (5, 30181.0)    (6, 32288.0)    (7, 33836.0)    (8, 35003.0)    (9, 35893.0)    (10, 36576.0)




Rrox
(2, 16310.0)    (3, 24465.0)    (4, 30093.0)    (5, 34458.0)    (6, 38048.0)    (7, 41106.0)    (8, 43774.0)    (9, 46140.0)    (10, 48268.0)   (11, 50200.0)   (12, 51968.0)   (13, 53599.0)(14, 55110.0)   (15, 56519.0)   (16, 57837.0)   (17, 59076.0)   (18, 60244.0)   (19, 61349.0)   (20, 62396.0)   (21, 63393.0)   (22, 64342.0)   (23, 65249.0)   (24, 66117.0)   (25, 66949.0)(26, 67748.0)   (27, 68517.0)   (28, 69257.0)   (29, 69972.0)   (30, 70662.0)   (31, 71329.0)   (32, 71975.0)   (33, 72601.0)   (34, 73209.0)   (35, 73799.0)   (36, 74372.0)   (37, 74930.0)(38, 75474.0)   (39, 76003.0)   (40, 76519.0)   (41, 77023.0)   (42, 77515.0)   (43, 77996.0)   (44, 78465.0)   (45, 78925.0)   (46, 79375.0)   (47, 79816.0)   (48, 80248.0)   (49, 80671.0)(50, 81086.0)   (51, 81494.0)   (52, 81894.0)   (53, 82287.0)   (54, 82673.0)   (55, 83052.0)   (56, 83425.0)   (57, 83792.0)   (58, 84153.0)   (59, 84508.0)   (60, 84858.0)   (61, 85202.0)(62, 85542.0)   (63, 85876.0)   (64, 86206.0)   (65, 86531.0)   (66, 86852.0)   (67, 87168.0)   (68, 87480.0)   (69, 87789.0)   (70, 88093.0)   (71, 88393.0)   (72, 88690.0)   (73, 88983.0)(74, 89272.0)   (75, 89559.0)   (76, 89842.0)   (77, 90121.0)   (78, 90398.0)   (79, 90671.0)   (80, 90942.0)   (81, 91210.0)   (82, 91475.0)   (83, 91737.0)   (84, 91996.0)   (85, 92253.0)(86, 92508.0)   (87, 92760.0)   (88, 93009.0)   (89, 93257.0)   (90, 93501.0)   (91, 93744.0)   (92, 93984.0)   (93, 94223.0)   (94, 94459.0)   (95, 94693.0)   (96, 94925.0)   (97, 95155.0)(98, 95384.0)   (99, 95610.0)   (100, 95835.0)  (101, 96057.0)  (102, 96278.0)  (103, 96498.0)  (104, 96715.0)  (105, 96931.0)  (106, 97145.0)  (107, 97358.0)  (108, 97569.0)  (109, 97778.0)       (110, 97986.0)  (111, 98193.0)  (112, 98398.0)  (113, 98602.0)  (114, 98804.0)


It seems that for my 5 populations the best sample size used in --proj flag are 4,70,12,10 and 114. So i rerun the easySFS.py to infer the SFS results. When i checked my result files i found for the "XXX__jointDAFpop4_1.obs" file ,there are too many "0" values in the joint SFS matrix, it looks like :


1 observation
        d1_0    d1_1    d1_2    d1_3    d1_4    d1_5    d1_6    d1_7    d1_8    d1_9    d1_10   d1_11   d1_12   d1_13   d1_14   d1_15   d1_16   d1_17   d1_18   d1_19   d1_20   d1_21   d1_22
d4_0    75951 10533 7066 5404 4268 3560 3091 2804 2436 2193 1955 1816 1630 1401 1315 1244 1097 1001 932 901 845 743 722 668 614 590 541 505 509 476 442 420 370 375 364 363 323 315 280 310 3
d4_1    177 179 172 168 161 176 155 169 135 139 161 139 168 171 153 142 150 185 184 159 163 152 167 148 166 178 164 193 187 182 194 171 176 189 179 195 199 208 261 284 358 817 4773 23070 14
d4_2    1 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 1 2 0
d4_3    1 0 0 0 0 0 0 0 1 3 0 1 0 0 3 16 54 1101 30 15 21 8 8 2 8 2 2 2 0 2 1 0 1 2 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0
d4_4    0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 2 0 0 10 19 952 10 9 6 9 9 4 4 0 3
d4_5    3 5 2 0 2 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
d4_6    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 2 21 810 11 5 7 6 6 2 2 0 4 4 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0
d4_7    0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
d4_8    0 0 2 0 1 3 21 707 6 3 4 2 1 2 1 1 2 0 0 1 0 3 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 2 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
d4_9    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 3 21 693 4 1 1 1 5 3 2 2 2 1 1 1 2 0 0 0 1 0 2
d4_10   1 2 1 1 0 0 1 0 0 2 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
d4_11   0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 29 586 3 3 0 2 0 2 0 5 1 1 0 1 2 0 2 0 1 1 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
d4_12   1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 24 600 5 0
d4_13   0 2 0 0 0 2 1 4 2 0 1 0 1 3 2 0 2 1 2 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 2 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0
d4_14   0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 18 523 1 2 0 2 0 2 0 1 1 1 1 4 2 0 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0
d4_15   0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
d4_16   0 0 0 1 0 0 0 0 0 0 0 1 4 23 485 1 2 0 1 2 1 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1
d4_17   0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 7 17 456 4 1 0 0 0 0 1 0 1 0 2 0
d4_18   1 1 1 1 3 0 0 0 0 1 0 2 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
d4_19   0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 5 22 448 10 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0
d4_20   0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
d4_21   0 0 4 20 398 8 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
d4_22   0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 2 0 0 0 0 0 0 1 0 0 1 1 2 23 381 4 0 0 0 0 0 0 0 0 0 0 0 0 0 1 3 0 0 2 1 1 1
d4_23   0 1 0 2 1 0 3 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
d4_24   0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 8 18 379 4 0 0 1 0 1 1 0 0 1 0 0 1 0 0 1 0 0 0 2 1 1 2 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0
d4_25   0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 4 17 399 6 1 1 0 0
d4_26   0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
d4_27   1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 2 19 324 7 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 2 0 0 0 0
d4_28   0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 2 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
d4_29   0 0 0 0 1 0 0 0 1 3 24 310 7 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 2 1 0 0 0 2 1 0 1 2 0 0 0 0 1 2 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0
d4_30   0 0 0 0 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 20 295 6 1 1 0 0 1 0 2 0 1 0 0 0 1 0
d4_31   0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 1 3 1 0 0 2 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0
d4_32   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 24 331 8 3 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0
d4_33   1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 2
d4_34   24 283 14 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 2 1 1 1 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
d4_35   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 4 26 297 10 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
d4_36   1 1 0 0 1 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
d4_37   0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 5 20 291 4 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 2 1 0 1 2 0 0 1 0 0 1 0 0 0
d4_38   0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 27 272 11 1 1 0 0 0 0 0
d4_39   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 2 0 0 1 1 3 0 0 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
d4_40   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 15 310 11 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 2 1 1


So did i miss some improtant things during my data processing ? And whether this pattern is normal ?  Thanks again ! Looking forward your reply.
Best Wishes.

At 2019-09-26 23:37:07, "Isaac Overcast" <notifications@github.com> wrote:


Hello,
The --proj values should be set to maximize the number of segregating sites, which you can evaluate with the --preview flag. The values for --proj that you suggest are valid, and these will retain only sites that are present in all samples.

**Comment by isaacovercast** [comment]
The 0 values just mean that there are no snps in that joint frequency class. What it looks like is that there's just not a lot of SNPs that segregate in both populations (lots of sites that are monomorphic in one or the other).

**Comment by Yun-HongWu** [comment]
Dear Isaac, thanks again for your reply. But i'm still confused by a phnomenon, when i change the --proj set  (such as  -proj=4,20,12,10,20 ) to infer the joint SFSs of the 5 populations.  For the same population pair (as mentioned in my previous comment "XXX__jointDAFpop4_1.obs"), I found the "0" values are almost move out from the joint SFS matrix, and the results looks like this :
1 observation
        d1_0    d1_1    d1_2    d1_3    d1_4    d1_5    d1_6    d1_7    d1_8    d1_9    d1_10   d1_11   d1_12   d1_13   d1_14   d1_15   d1_16   d1_17   d1_18   d1_19   d1_20
d4_0    101805 16213 9042 5793 3986 2902 2227 1796 1516 1325 1189 1088 1011 954 918 904 913 946 1038 2144 28383
d4_1    2799 58 26 14 9 6 4 4 3 3 3 2 2 2 1 2 2 2 2 7 101
d4_2    2019 26 16 11 8 6 5 4 3 3 2 2 1 1 1 1 1 1 2 5 87
d4_3    1613 15 11 9 7 6 5 4 3 3 2 2 1 1 1 1 1 1 2 4 85
d4_4    1357 11 7 7 6 6 5 4 4 3 2 2 1 1 1 1 1 1 1 4 84
d4_5    1186 9 5 5 6 6 5 5 5 4 3 2 2 1 1 1 1 1 1 4 84
d4_6    1071 9 4 4 5 5 6 6 6 6 5 4 3 2 1 1 1 1 1 4 85
d4_7    990 9 3 3 4 5 6 7 9 9 9 7 5 3 2 1 1 1 1 4 85
d4_8    929 10 2 3 3 4 6 9 12 14 14 12 8 5 3 2 1 1 1 4 86
d4_9    879 10 2 2 3 4 6 10 14 18 18 16 11 7 4 2 1 1 1 3 86
d4_10   831 10 2 2 2 3 6 10 15 19 20 18 13 8 4 2 1 1 1 3 86
d4_11   785 11 2 2 2 3 5 8 12 16 17 16 12 8 4 2 2 1 1 3 87
d4_12   743 12 2 1 1 2 3 5 8 11 12 12 9 6 4 2 2 1 2 3 87
d4_13   710 13 2 1 1 1 2 3 5 6 7 7 6 5 3 2 2 2 2 3 89
d4_14   690 14 2 1 1 1 1 2 3 3 4 4 4 3 3 2 2 2 2 3 94
d4_15   683 15 2 1 1 1 1 1 2 2 2 3 3 2 2 2 2 2 2 3 102
d4_16   682 16 2 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 112
d4_17   686 18 2 1 1 1 1 1 1 1 1 1 1 2 2 2 2 3 3 5 123
d4_18   695 20 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 3 4 7 142
d4_19   736 22 2 1 1 1 1 1 1 1 1 1 1 1 2 2 3 4 7 15 292
d4_20   30283 1167 171 125 111 104 99 97 98 102 106 112 119 129 147 176 222 298 436 1038 15119

But for the same population pair ,with the --proj=4,70,12,10,114 set, for the same joint frequency class, such as： d4_2 <-->d1_0  in --proj=4,20,12,10,114 the number of segregate sites is 1 but in --proj=4,20,12,10,20 the number  is 2019. Could you tell me the reasons underlying these difference?  And whether these joint SFS matrixs with such more "0" values can be used into our subsequent Fsc26 analysis ? Looking forward  to your replys or suggestions . Best Wishes !

**Comment by isaacovercast** [comment]
The difference is because if you require more samples to be in the 5th population (114) then more sites will be thrown out because of missing data (you can only project down to smaller sample size, not up to larger). This is the _reason_ for the --preview flag procedure. SFS matrices can certainly have 0 value bins, this is not a problem at all, especially with 5 population, you will expect the multiSFS to be quite sparse.
