### ISSUE TITLE
missing data and projection values

### ISSUE THREAD

**Issue by angelesdecara** [isaacovercast/easySFS#22]
Hi!

Many thanks for all your help! I'm trying to figure out whether some values that I'm obtaining in trials of fastsimcoal come from a weird SFS.
I've computed a MSFS projecting to balanced samples (40,40,40,40) for four populations (I have 29,32,22 and 24 individuals of each population). As far as I can see, the only entry of the MSFS that is greater than one is the first one. 
How does easySFS handle missing data? 
Is it normal that the MSFS has such values?

Many thanks for all your help!

**Comment by isaacovercast** [comment]
Did you perform the `--preview` part of the procedure? This shows you all the combinations of projection levels. If you have lots of missing data and force the sample size to (40,40,40,40), then yeah you'll end up with almost no data in your msfs. easySFS uses the dadi hypergeometric projection internally to 'average over' missing data. You should probably consider looking at the results of `--preview` and choosing smaller values for the projection.

**Comment by angelesdecara** [comment]
I've performed preview and removed a SNP that was sexual and had lots of missing but was not being reported by plink.
I've forced it to (34,36,20,28). Now it seems all entries are smaller than 1 even the first one. What I'm still trying to understand is whether fastsimcoal will deal properly with such SFS as the -C flag seems to discard all entries lower than 1 by default.
Sorry this is a mixed issue between fatsimcoal and easySFS and probably my own mistakes and misunderstandings...
Thanks a lot!

**Comment by isaacovercast** [comment]
What are the results of --preview? As I recall, once you get more than 3
populations the msfs starts to get really sparse, so the recommendation is
to use the pairwise joint sfs files, but the msfs should still work. How
closely related are these populations? How many seg sites is preview
telling you get for that projection level?

**Comment by angelesdecara** [comment]
Here are the results from --preview:

P09
(2, 5.0)        (3, 8.0)        (4, 10.0)       (5, 11.0)       (6, 12.0)       (7, 12.0)       (8, 13.0)   (9, 13.0)        (10, 14.0)      (11, 14.0)      (12, 14.0)      (13, 14.0)      (14, 14.0)      (15, 14.0)  (16, 15.0)       (17, 15.0)      (18, 15.0)      (19, 15.0)      (20, 15.0)      (21, 15.0)      (22, 15.0)  (23, 15.0)       (24, 15.0)      (25, 15.0)      (26, 15.0)      (27, 15.0)      (28, 15.0)      (29, 15.0)  (30, 15.0)       (31, 15.0)      (32, 15.0)      (33, 15.0)      (34, 16.0)      (35, 16.0)      (36, 16.0)  (37, 16.0)       (38, 16.0)      (39, 16.0)      (40, 16.0)      (41, 16.0)      (42, 16.0)      (43, 16.0)  (44, 16.0)       (45, 16.0)      (46, 16.0)      (47, 16.0)      (48, 16.0)      (49, 16.0)      (50, 16.0)  (51, 16.0)       (52, 16.0)      (53, 16.0)      (54, 16.0)      (55, 16.0)      (56, 16.0)      (57, 16.0)  (58, 16.0)

P15
(2, 6.0)        (3, 9.0)        (4, 11.0)       (5, 12.0)       (6, 12.0)       (7, 13.0)       (8, 13.0)   (9, 14.0)        (10, 14.0)      (11, 14.0)      (12, 14.0)      (13, 14.0)      (14, 14.0)      (15, 15.0)  (16, 15.0)       (17, 15.0)      (18, 15.0)      (19, 15.0)      (20, 15.0)      (21, 15.0)      (22, 15.0)  (23, 15.0)       (24, 15.0)      (25, 15.0)      (26, 15.0)      (27, 15.0)      (28, 15.0)      (29, 15.0)  (30, 15.0)       (31, 15.0)      (32, 15.0)      (33, 15.0)      (34, 15.0)      (35, 16.0)      (36, 16.0)  (37, 16.0)       (38, 16.0)      (39, 16.0)      (40, 16.0)      (41, 16.0)      (42, 16.0)      (43, 16.0)  (44, 16.0)       (45, 16.0)      (46, 16.0)      (47, 16.0)      (48, 16.0)      (49, 16.0)      (50, 16.0)  (51, 16.0)       (52, 16.0)      (53, 16.0)      (54, 16.0)      (55, 16.0)      (56, 16.0)      (57, 16.0)  (58, 16.0)       (59, 16.0)      (60, 16.0)      (61, 15.0)      (62, 15.0)      (63, 14.0)      (64, 14.0)

P17
(2, 5.0)        (3, 8.0)        (4, 10.0)       (5, 11.0)       (6, 12.0)       (7, 12.0)       (8, 13.0)   (9, 13.0)        (10, 13.0)      (11, 13.0)      (12, 14.0)      (13, 14.0)      (14, 14.0)      (15, 14.0)  (16, 14.0)       (17, 14.0)      (18, 14.0)      (19, 14.0)      (20, 15.0)      (21, 15.0)      (22, 15.0)  (23, 15.0)       (24, 15.0)      (25, 15.0)      (26, 15.0)      (27, 15.0)      (28, 15.0)      (29, 15.0)  (30, 15.0)       (31, 15.0)      (32, 15.0)      (33, 15.0)      (34, 15.0)      (35, 15.0)      (36, 15.0)  (37, 15.0)       (38, 15.0)      (39, 14.0)      (40, 14.0)      (41, 14.0)      (42, 14.0)      (43, 14.0)  (44, 14.0)

RUWB3
(2, 6.0)        (3, 10.0)       (4, 12.0)       (5, 13.0)       (6, 14.0)       (7, 14.0)       (8, 15.0)   (9, 15.0)        (10, 15.0)      (11, 15.0)      (12, 16.0)      (13, 16.0)      (14, 16.0)      (15, 16.0)  (16, 16.0)       (17, 16.0)      (18, 16.0)      (19, 16.0)      (20, 16.0)      (21, 16.0)      (22, 16.0)  (23, 16.0)       (24, 16.0)      (25, 16.0)      (26, 16.0)      (27, 17.0)      (28, 17.0)      (29, 17.0)  (30, 17.0)       (31, 17.0)      (32, 17.0)      (33, 17.0)      (34, 17.0)      (35, 17.0)      (36, 17.0)  (37, 17.0)       (38, 17.0)      (39, 17.0)      (40, 17.0)      (41, 17.0)      (42, 17.0)      (43, 17.0)  (44, 17.0)       (45, 17.0)      (46, 17.0)      (47, 17.0)      (48, 17.0)

Thanks!

**Comment by angelesdecara** [comment]
Sorry, I forgot to answer about how closely related they are... They can still interbreed, I think, so I'd say quite related! These are data from SNP chips and have been filtered to have maximum missing of 0.1 with plink.

**Comment by isaacovercast** [comment]
Yeah, well something is goofy, as you can see the numbers of segregating
sites are very very very small. The meaning of the (x, y) values are #
samples to project to (x) and resulting # of segsites (y). As you can see,
at all projection levels youre only retaining a dozen or so segsites.
Something must be up with your data.

**Comment by angelesdecara** [comment]
For those who experience similar issues in the future:

my problem was in not using the -a flag to use all SNPs in my data set (which are not from RADseq and had already been filtered).

I've no idea what easySFS was doing without the flag, but I could see lots of segregating sites. Now it's all sorted out, I hope!

**Comment by isaacovercast** [comment]
Thanks for following up Angela. W/o the -a flag easysfs selects 1 snp per 'locus', which if it was not radseq data would probably treat each chromosome/scaffold as a locus.

**Comment by EveTC** [comment]
@angelesdecara - I think I am having the amse problem as you. I know this is an old post now but can you remeber if you thinned your data before carrying out easySFS? Thank you!

**Comment by isaacovercast** [comment]
@EveTC Did you do the --preview? Did you use the -a flag? What kind of 'thinning' do you mean exactly?

**Comment by EveTC** [comment]
Hi @isaacovercast, thank you for your speeding response!

I originally missed the `-a` whilst running the `--preview` so recieved very low numbers as @angelesdecara above. My data is WGS (although at quite low coverage). By thinning I mean removing any sites that may be linked? E.g. using `vcftools --thin` or similar. Unless easySFS removes the issue of linkage? I am very new to the realm of SFS etc - appologies if I am misunderstanding the method.

Thank you for such a great package!

**Comment by isaacovercast** [comment]
@EveTC Thanks for the positive feedback! easySFS doesn't do any LD pruning, so if you want to remove linked sites then using vcftools as you suggest would be an effective strategy. Good luck!

**Comment by EveTC** [comment]
Ah I thought so - fantastic - Thank you so much!

A quick question - how do I know how many loci are left after I have run easySFS? Is it the total of the segretating sites that I have selected from the --preview?

**Comment by isaacovercast** [comment]
easySFS only considers variable sites (SNPs), so after you run it there's not really a good sense of how many 'loci' are used.

In your example, the difference between the total (58k) and the observed number is because many of the sites will be shared across populations.

**Comment by EveTC** [comment]
Ah yes thats true. I see - FastSimCoal2 recommends having over 8000/10000 so perhaps I will just cross my fingers and hope that this is the case in my data! Haha

**Comment by isaacovercast** [comment]
Good luck!

**Comment by EveTC** [comment]
Thank you so much for your help! I hope you have a lovely weekend :)
