### ISSUE TITLE
file names in fastsimcoal2 folder

### ISSUE THREAD

**Issue by smallfishcui** [isaacovercast/easySFS#23]
Hi,

I was running easySFS to get the site frequency spectrum for plant populations. I assigned the individuals to the populations, and it performed well in dadi, and the naming system is clear, so I got files like this:  EU-CN.sfs  EU-Usland.sfs  Med-8.sfs   Med-EU.sfs
However in the fastsimcoal2 folder, I get proper files but the naming system is not informative at all, for example,  I have eight populations, and I gave a prefix like biallelic, then I got files like this:biallelic_jointMAFpop3_1.obs  biallelic_jointMAFpop4_3.obs  biallelic_jointMAFpop5_4.obs  biallelic_jointMAFpop6_4.obs 
How do I know which one is pop1, pop2 or pop3, is it possible to get a name as I specified in the population file?

thanks,
Cui

**Comment by isaacovercast** [comment]
You will have to talk to Excoffier about these goofy file names. I am only following the spec from fastsimcoal2. The index of each population retained from the order in which they are presented to easySFS. I know this is annoying, but this is fsc2 required file names format.
