### ISSUE TITLE
multiSFS building fails

### ISSUE THREAD

**Issue by meganlsmith** [isaacovercast/easySFS#30]
Hi Isaac,
First, thanks for making this incredibly useful tool! I am trying to use easySFS to build a multidimensional SFS for ten populations. However,  when I run the script to construct the SFS, it builds all the 2D sfs, but when it goes to build the multidimensional SFS, it hangs up for a moment and then returns: "Killed: 9". I'm emailing to see if you may know what would cause this issue. Below, I provide the command I am running, and I have included the vcf and the populations file. Thanks in advance for any insight you have!

Command: ./easySFS/easySFS.py -i Dendro_m76.vcf -p traits.txt --proj=4,2,16,8,20,4,6,52,28,20 -f

[Archive.zip](https://github.com/isaacovercast/easySFS/files/4701949/Archive.zip)

**Comment by isaacovercast** [comment]
Hey Megan,
Thanks for the positive feedback! I am going to _guess_ this is a memory limitation issue. I've seen this before when people try to construct massive multi-population SFS. It's not the number of samples so much as the number of populations. Each time you add a population you're creating an entirely new dimension of the SFS, so the size grows exponentially with # of populations. The SFS you want to create would have 14 billion bins. I would recommend choosing smaller values for the 52, 28, and 20 populations, as a start. Hope that helps!

**Comment by meganlsmith** [comment]
Hi Isaac,
Thanks for the quick reply! You were correct; it was a memory issue I believe. Adjusting those values fixed the problem. 
Best,
Megan
