### ISSUE TITLE
Which individuals were used to calculate the SFS

### ISSUE THREAD

**Issue by Jolvii85** [isaacovercast/easySFS#31]
Hi, 
I would like to know which individuals were used to calculate the final SFS of each population, can you tell me how to get this information?

Thanks.

**Comment by isaacovercast** [comment]
If you used the `--proj` to downproject to a smaller number of samples then this is not a meaningful question. During the projection procedure the snp frequencies are kind of 'averaged over' all possible subsamplings to the projection level specified. The sfs you get with the --proj is a composite of the snp frequencies of all the samples. Hope that helps.

**Comment by Jolvii85** [comment]
Thanks for your explanation, that makes sense. 

I have another question, do you use all the snps (including non-polymorphism ones) in the vcf file? For dadi, we need to know L (total length of sequence used to discover SNPs) to calculate the specific parameters.

Best regards.

**Comment by isaacovercast** [comment]
monomorphic sites are included in the output sfs, if they are present in the vcf. Does that answer your question?

**Comment by Jolvii85** [comment]
That means, The final SFS was calculated based on all the samples and snps (also including missing ones) in the vcf file?

**Comment by Jolvii85** [comment]
Actually, I just do not know how does this script do the downsampling.

**Comment by isaacovercast** [comment]
The SFS can't include missing data, which is the exact point of the
hypergeometric projection method.

**Comment by isaacovercast** [comment]
You may find this information in the supplement to the dadi manuscript
<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2760211/#pgen.1000695.s001>.

**Comment by Jolvii85** [comment]
Thanks a lot!!! Now I know everything I want to know.
