### ISSUE TITLE
easySFS removes existing directories if the user is not careful with the -o flag

### ISSUE THREAD

**Issue by wyoibc** [isaacovercast/easySFS#34]
I just made the silly mistake of setting the output directory to an existing one and all of my data was overwritten by easySFS.

Case in point:

```
output=/project/sfs/demography
easysfs.py -o $output
```

I realize I needed to set it to ``$output/easysfs_out``, but it would be good to produce an error and quit if the directory already exists.

**Comment by isaacovercast** [comment]
Hello there. Ouch, yeah that sucks, not a good situation get overwrite data. There already is a `-f` force flag which guards against overwriting existing directories, but still the behavior is a little careless. I fixed this so if you pass in an existing directory with stuff in it it will only overwrite the files created by easySFS and will leave everything else untouched.
