### ISSUE TITLE
--proj

### ISSUE THREAD

**Issue by schnappi-wkl** [isaacovercast/easySFS#35]
Hi,
isaac, i don't understand how to set the values of --proj.  can you  tell me it by the example of "--proj-- 12, 20 ".
Otherwise, can i set each populations individuals numbers as proj?

**Comment by isaacovercast** [comment]
Did you try this: `--proj 12,20`

**Comment by schnappi-wkl** [comment]
if i have three populations including 10，15，20 individuals respectively， should i set “--proj” values as “--proj 10，15，20”？
Thanks

**Comment by isaacovercast** [comment]
Yes, that's right, but no spaces between the digits `--proj 10,15,20`.
