### ISSUE TITLE
ancestral stat add

### ISSUE THREAD

**Issue by sunshichao0916** [isaacovercast/easySFS#36]
Hi Isaac,
    It's really a nice tool.  After reading README.md, I know --unfolded parameter can generate an unfolded SFS, but  where should I add the ancestor stat in my VCF file? 

Best

**Comment by isaacovercast** [comment]
Hello, if you use the `--unfolded` parameter then easySFS simply assumes the REF allele in the vcf file is ancestral. The vcf file should be created with the ancestral state coded in the REF column.
