### ISSUE TITLE
how can I choose the projection values

### ISSUE THREAD

**Issue by zilaijuand** [isaacovercast/easySFS#39]
Hi @isaacovercast,
  thank you so much for developing so many useful software！
  I want to simulate the population history by using the stairway plot2 and fastsimcol2. I got 84 samples divided into three populations(The number of each populations is 69,11,4). The following is  preview (--preview) of 1D SFS and 3D SFS. So how can I choose the projection values to fit the stairway plot and fastsimcol？Is it  just to select the number of each population？ like 
--proj 84 and --proj 69，11，4？

#Treat all samples as one population to run stairway plot
./easySFS.py -i populations.snps.vcf -p popmapsum.txt -a --preview 

Processing 1 populations - odict_keys(['pop1'])

pop1
(2, 1030)       (3, 1545)       (4, 1980)       (5, 2376)       (6, 2744)       (7, 3089)       (8, 3415)       (9, 3725)       (10, 4020)      (11, 4302)      (12, 4572)  (13, 4831)      (14, 5081)      (15, 5321)      (16, 5552)      (17, 5776)      (18, 5992)      (19, 6201)      (20, 6403)      (21, 6599)      (22, 6789) (23, 6973)       (24, 7152)      (25, 7326)      (26, 7495)      (27, 7659)      (28, 7819)      (29, 7974)      (30, 8126)      (31, 8273)      (32, 8417)      (33, 8557)  (34, 8693)      (35, 8826)      (36, 8956)      (37, 9083)      (38, 9206)      (39, 9327)      (40, 9445)      (41, 9560)      (42, 9672)      (43, 9782) (44, 9890)       (45, 9995)      (46, 10097)     (47, 10197)     (48, 10296)     (49, 10392)     (50, 10485)     (51, 10577)     (52, 10667)     (53, 10755)     (54, 10841) (55, 10925)     (56, 11008)     (57, 11088)     (58, 11167)     (59, 11245)     (60, 11320)     (61, 11395)     (62, 11467)     (63, 11538)     (64, 11608)(65, 11676)      (66, 11743)     (67, 11808)     (68, 11872)     (69, 11935)     (70, 11997)     (71, 12057)     (72, 12116)     (73, 12174)     (74, 12230)     (75, 12286) (76, 12340)     (77, 12393)     (78, 12445)     (79, 12496)     (80, 12546)     (81, 12595)     (82, 12643)     (83, 12689)     (84, 12735)     (85, 12780)(86, 12824)      (87, 12867)     (88, 12909)     (89, 12950)     (90, 12991)     (91, 13030)     (92, 13069)     (93, 13106)     (94, 13143)     (95, 13179)     (96, 13214) (97, 13249)     (98, 13283)     (99, 13315)     (100, 13348)    (101, 13379)    (102, 13410)    (103, 13439)    (104, 13469)    (105, 13497)    (106, 13525)(107, 13552)    (108, 13578)    (109, 13604)    (110, 13629)    (111, 13654)    (112, 13677)    (113, 13701)    (114, 13723)    (115, 13745)    (116, 13766)    (117, 13787)        (118, 13807)    (119, 13827)    (120, 13846)    (121, 13864)    (122, 13882)    (123, 13899)    (124, 13916)    (125, 13932)    (126, 13947)    (127, 13962)        (128, 13977)    (129, 13991)    (130, 14004)    (131, 14017)    (132, 14030)    (133, 14042)    (134, 14053)    (135, 14064)    (136, 14075)    (137, 14085)        (138, 14094)    (139, 14103)    (140, 14112)    (141, 14120)    (142, 14128)    (143, 14130)    (144, 14137)    (145, 14128)    (146, 14134)    (147, 14080)        (148, 14085)    (149, 13950)    (150, 13954)    (151, 13653)    (152, 13656)    (153, 13086)    (154, 13089)    (155, 12239)    (156, 12241)    (157, 11018)        (158, 11020)    (159, 9401)     (160, 9402)     (161, 7518)     (162, 7518)     (163, 5413)     (164, 5414)     (165, 3346)     (166, 3346)     (167, 1514) (168, 1514)

#making 3D SFS
./easySFS.py -i populations.snps.vcf -p popmap.txt -a --preview
Processing 3 populations - odict_keys(['pop1', 'pop2', 'pop3'])
pop1
(2, 959)        (3, 1438)       (4, 1841)       (5, 2205)       (6, 2543)       (7, 2858)       (8, 3156)       (9, 3437)       (10, 3705)      (11, 3961)      (12, 4205)  (13, 4439)      (14, 4664)      (15, 4880)      (16, 5088)      (17, 5288)      (18, 5482)      (19, 5669)      (20, 5849)      (21, 6024)      (22, 6194) (23, 6358)       (24, 6517)      (25, 6671)      (26, 6821)      (27, 6967)      (28, 7109)      (29, 7246)      (30, 7380)      (31, 7510)      (32, 7637)      (33, 7761)  (34, 7881)      (35, 7998)      (36, 8112)      (37, 8224)      (38, 8332)      (39, 8438)      (40, 8542)      (41, 8642)      (42, 8741)      (43, 8837) (44, 8931)       (45, 9022)      (46, 9111)      (47, 9199)      (48, 9284)      (49, 9367)      (50, 9448)      (51, 9528)      (52, 9606)      (53, 9681)      (54, 9755)  (55, 9828)      (56, 9899)      (57, 9968)      (58, 10035)     (59, 10102)     (60, 10166)     (61, 10229)     (62, 10291)     (63, 10351)     (64, 10410)(65, 10467)      (66, 10524)     (67, 10579)     (68, 10632)     (69, 10685)     (70, 10736)     (71, 10786)     (72, 10835)     (73, 10883)     (74, 10929)     (75, 10975) (76, 11019)     (77, 11062)     (78, 11105)     (79, 11146)     (80, 11186)     (81, 11225)     (82, 11264)     (83, 11301)     (84, 11337)     (85, 11373)(86, 11407)      (87, 11441)     (88, 11474)     (89, 11506)     (90, 11537)     (91, 11567)     (92, 11596)     (93, 11625)     (94, 11653)     (95, 11680)     (96, 11706) (97, 11731)     (98, 11756)     (99, 11780)     (100, 11803)    (101, 11825)    (102, 11847)    (103, 11868)    (104, 11888)    (105, 11908)    (106, 11927)(107, 11945)    (108, 11963)    (109, 11980)    (110, 11996)    (111, 12012)    (112, 12027)    (113, 12041)    (114, 12055)    (115, 12068)    (116, 12080)    (117, 12082)        (118, 12094)    (119, 12065)    (120, 12076)    (121, 11955)    (122, 11964)    (123, 11652)    (124, 11660)    (125, 11072)    (126, 11079)    (127, 10129)        (128, 10135)    (129, 8808)     (130, 8813)     (131, 7138)     (132, 7141)     (133, 5188)     (134, 5191)     (135, 3292)     (136, 3293)     (137, 1481) (138, 1481)

pop2
(2, 844)        (3, 1267)       (4, 1554)       (5, 1773)       (6, 1951)       (7, 2099)       (8, 2226)       (9, 2335)       (10, 2431)      (11, 2516)      (12, 2591)  (13, 2658)      (14, 2718)      (15, 2772)      (16, 2820)      (17, 2863)      (18, 2902)      (19, 2397)      (20, 2424)      (21, 1531)      (22, 1546)

pop3
(2, 454)        (3, 681)        (4, 820)        (5, 915)        (6, 987)        (7, 1046)       (8, 1098)

Thanks.

**Comment by isaacovercast** [comment]
Glad you like easySFS! For selecting the number of samples for the `--proj` you should choose the number of samples that maximizes the number of segregating sites, so for example you can choose `--proj 99` or `--proj 150` or anywhere between. For the second example it might look like `--proj, 118,18,7`. But there is a tradeoff between number of SNPs in the sfs and performance, sometimes, so you will have to tune these values for your needs. Good luck!

**Comment by zilaijuand** [comment]
Thank you for answering this! So if I choose  the --proj, 118,18,7, should my 3populations.tml files in fastsimcoal written like this?

//Parameters for the coalescence simulation program : fastsimcoal.exe
3 samples to simulate :
//Samples sizes and samples age
118
18
7

or just write the real samples size?
//Samples sizes and samples age
69
11
4

**Comment by isaacovercast** [comment]
It's haploid samples, so the first one is correct. Good luck!
