### ISSUE TITLE
Zero DAF frequency bin grows in small projections

### ISSUE THREAD

**Issue by OliverPStuart** [isaacovercast/easySFS#40]
Hi,

Projecting down to smaller and smaller sample sizes, I find that the number of sites in the first frequency bin (i.e. invariant) grows larger. Is this some feature of the math used in the projection, e.g. a site with derived allele frequency of 1/80 gets projected to 0/30, or something like that? 

Best,
Ollie

**Comment by isaacovercast** [comment]
Hi Ollie,
Yes, that's exactly right. As the sample size decreases rare variants get lost, essentially collapsed into the invariant sites bin. This is just a natural outcome of the down-projection procedure. Hope that helps!
All the best,
-isaac
