### ISSUE TITLE
how to interpret results

### ISSUE THREAD

**Issue by selasphoruskershaw** [isaacovercast/easySFS#42]
Hello,

I successfully ran easySFS on all of my populations, but for each population there is an extra number.

For example, in one population's output (15 diploid individuals), I get the following, which is 31 total numbers and 16 non-zero numbers: 12875322 432991 274827 201109 139712 107003 107935 72349 62181 58143 56489 56319 57759 62285 77825 75672 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

How do I enter these values into a program such as Stairwayplot2? I have 15 individuals and the software forces me to have 15 numbers inputted for the SFS.

Thank you for your help!

**Comment by isaacovercast** [comment]
The first number in the list is monomorphic sites, which I believe stairwayplot does not consider. Take the 2nd through the 16th numbers and remove all the 0s and you will have the SFS bins that stairwayplot wants. Good luck!

**Comment by selasphoruskershaw** [comment]
This worked, thank you!
