### ISSUE TITLE
run easySFS.py error

### ISSUE THREAD

**Issue by chenqing-1996** [isaacovercast/easySFS#43]
hello isaacovercast,
I had a question when I run easySFS.py, following:
Traceback (most recent call last):
  File "/home/ch/miniconda3/easySFS/easySFS.py", line 677, in <module>
    main()
  File "/home/ch/miniconda3/easySFS/easySFS.py", line 633, in main
    dd = make_datadict(genotypes, pops=pops, ploidy=args.ploidy, verbose=args.verbose)
  File "/home/ch/miniconda3/easySFS/easySFS.py", line 295, in make_datadict
    pop_genotypes = [row[x].split(":")[0] for x in pops[pop]]
  File "/home/ch/miniconda3/easySFS/easySFS.py", line 295, in <listcomp>
    pop_genotypes = [row[x].split(":")[0] for x in pops[pop]]
AttributeError: 'NoneType' object has no attribute 'split'

I didn't know how to solve it. Looking forward to your reply.

**Comment by isaacovercast** [comment]
It looks like an problem with your population assignment file. What does your pop assignment file look like? Also it is helpful to see the full command line run when the error happens.

**Comment by chenqing-1996** [comment]
Hi isaacovercast,
My pop file is:
SC01W	pop1
SC02W	pop1
SC03W	pop1
SC04W	pop1
SC05W	pop1
sample_SC02A		pop2
sample_SC03A		pop2
sample_SC04A		pop2
sample_SC05A		pop2

In fact, I suspected my VCF file was error, it is not output by pyrad or ipyrad.

**Comment by chenqing-1996** [comment]
My command line is:

python3 /home/chq/miniconda3/easySFS/easySFS.py -i /home/chq/data/vcf/ne.vcf -p /home/chq/data/code/pop_file.txt --preview -a -o /home/chq/data/SFSresults

**Comment by chenqing-1996** [comment]
Hello isaacovercast,
I have converted my VCF file format, but the problem still exists, I don't know what causes it, how can I solve it?

**Comment by chenqing-1996** [comment]
Hello isaacovercast,
That's odd, because the previous error doesn't happen anymore when I remove the -a argument. Can't I use all my SNP loci for the calculation?
My command line is:
python3 /home/chq/miniconda3/easySFS/easySFS.py -i /home/chq/data/vcf/ne.vcf -p /home/chq/data/code/pop_file.txt --preview

**Comment by isaacovercast** [comment]
The vcf file must have an odd formatting still. Can you email me the vcf file and the pop_file.txt?

**Comment by chenqing-1996** [comment]
> The vcf file must have an odd formatting still. Can you email me the vcf file and the pop_file.txt?

I'm really sorry for replying to you so late. I have solved my problem. It is my data that contains missing loci. Thank you very much again.
