### ISSUE TITLE
No module named 'dadi'

### ISSUE THREAD

**Issue by XiaXiaTianTian** [isaacovercast/easySFS#49]
Hi, Isaac!

I'm using easySFS, but met the following error .`ModuleNotFoundError:` No module named 'dadi'`
I found  that it looks like a previous issue #17 
So I checked python version. It's `Python 3.6.5`,  and `conda list` showed I've installed `dadi`.

Thanks for your attention to this matter.

Best,
Xia

**Comment by isaacovercast** [comment]
Hello Xia,

Python 3.6 is a pretty old version, so you might try creating a new conda environment with a newer python version:

conda create -n easySFS_py310 python=3.10
conda activate easySFS_py310

And then install dadi and easySFS inside this conda env. I'm sure that will fix the problem.

Try this and let me know how it goes.

**Comment by XiaXiaTianTian** [comment]
Sorry. I tried but still failed in the same error.
`conda create -n easySFS_py310 python=3.10
conda activate easySFS_py310
mamba install dadi
mamba install pandas`

And `mamba list` shows versions are pandas  1.4.3 ； dadi 2.1.2 ;  python 3.10.5.

**Comment by isaacovercast** [comment]
I just tried this in a clean conda env and it worked fine for me:
```
conda create -n easySFS python=3.10
conda activate easySFs
git clone https://github.com/isaacovercast/easySFS.git
conda install -c conda-forge dadi pandas
cd easySFS/
./easySFS.py 
```

**Comment by isaacovercast** [comment]
Fixed?

**Comment by XiaXiaTianTian** [comment]
> Fixed?

I tried several times. I am sure your suggestion is correct. Because when some other softwares came into similar (No Module Named ""), they can be fixed using this solution.

**Comment by XiaXiaTianTian** [comment]
> Fixed?

I tried several times. I am sure your suggestion is correct. Because when some other softwares came into similar (No Module Named ""), they can be fixed using this solution.
But this time seem to not work.

**Comment by isaacovercast** [comment]
Can you show me the exact error message including the command line you type to generate it? Did you follow the exact instructions I posted? It _should_ work, so if it's not working maybe check your python path, it could be something funky with your local python configuration.

**Comment by isaacovercast** [comment]
I removed the dependency on the dadi module in the most recent version. fa521cd
