### ISSUE TITLE
choose the value of the projection

### ISSUE THREAD

**Issue by yuntwang** [isaacovercast/easySFS#5]
How can I select a best value and then return easySFS with the `--proj` flag

**Comment by isaacovercast** [comment]
This is pretty clearly documented already:

Each column is the number of samples in the projection and the number of segregating sites at that projection value. The dadi manual recommends maximizing the number of segregating sites, but at the same time if you have lots of missing data then you might have to balance # of segregating sites against # of samples to avoid downsampling too far.

Next run the script with the values for projecting for each population, like this:

./easySFS -i input.vcf -p pops_file.txt --proj 12,20

**Comment by yuntwang** [comment]
@isaacovercast  thanks for your reply.
I am sorry to disturb you again.
The preview mode:
./easySFS.py -i wcs_1200.vcf -p wcs_pops.txt -a --preview -f
nuttalli
(2, 141.0)	(3, 211.0)	(4, 260.0)	(5, 299.0)	(6, 331.0)	(7, 359.0)	(8, 383.0)	(9, 404.0)	(10, 424.0)	(11, 441.0)	(12, 457.0)	(13, 472.0)	(14, 486.0)	(15, 498.0)	(16, 510.0)	(17, 521.0)	(18, 531.0)	(19, 539.0)	(20, 548.0)	(21, 556.0)	(22, 564.0)	(23, 569.0)	(24, 577.0)	(25, 584.0)	(26, 590.0)	(27, 595.0)	(28, 601.0)	(29, 604.0)	(30, 609.0)	(31, 612.0)	(32, 617.0)	(33, 615.0)	(34, 619.0)	(35, 621.0)	(36, 625.0)	(37, 624.0)	(38, 627.0)	(39, 619.0)	(40, 622.0)	(41, 619.0)	(42, 622.0)	(43, 613.0)	(44, 616.0)	(45, 604.0)	(46, 607.0)	(47, 598.0)	(48, 600.0)	(49, 575.0)	(50, 577.0)	(51, 548.0)	(52, 550.0)	(53, 517.0)	(54, 519.0)	(55, 466.0)	(56, 468.0)	(57, 403.0)	(58, 404.0)	(59, 305.0)	(60, 306.0)	(61, 208.0)	(62, 209.0)	(63, 121.0)	(64, 121.0)	(65, 69.0)	(66, 69.0)	(67, 38.0)	(68, 38.0)	(69, 24.0)	(70, 24.0)	(71, 15.0)	(72, 15.0)	(73, 3.0)	


pugetensis
(2, 144.0)	(3, 216.0)	(4, 267.0)	(5, 308.0)	(6, 342.0)	(7, 372.0)	(8, 399.0)	(9, 423.0)	(10, 444.0)	(11, 464.0)	(12, 482.0)	(13, 500.0)	(14, 515.0)	(15, 530.0)	(16, 545.0)	(17, 558.0)	(18, 571.0)	(19, 583.0)	(20, 594.0)	(21, 605.0)	(22, 615.0)	(23, 625.0)	(24, 635.0)	(25, 644.0)	(26, 653.0)	(27, 661.0)	(28, 669.0)	(29, 677.0)	(30, 685.0)	(31, 692.0)	(32, 699.0)	(33, 706.0)	(34, 713.0)	(35, 718.0)	(36, 724.0)	(37, 730.0)	(38, 736.0)	(39, 742.0)	(40, 747.0)	(41, 753.0)	(42, 758.0)	(43, 763.0)	(44, 768.0)	(45, 772.0)	(46, 777.0)	(47, 782.0)	(48, 786.0)	(49, 790.0)	(50, 794.0)	(51, 797.0)	(52, 801.0)	(53, 805.0)	(54, 809.0)	(55, 813.0)	(56, 816.0)	(57, 820.0)	(58, 823.0)	(59, 826.0)	(60, 829.0)	(61, 831.0)	(62, 834.0)	(63, 837.0)	(64, 840.0)	(65, 843.0)	(66, 845.0)	(67, 848.0)	(68, 851.0)	(69, 853.0)	(70, 856.0)	(71, 856.0)	(72, 859.0)	(73, 861.0)	(74, 864.0)	(75, 865.0)	(76, 867.0)	(77, 867.0)	(78, 869.0)	(79, 871.0)	(80, 873.0)	(81, 872.0)	(82, 874.0)	(83, 876.0)	(84, 878.0)	(85, 879.0)	(86, 881.0)	(87, 882.0)	(88, 884.0)	(89, 885.0)	(90, 886.0)	(91, 887.0)	(92, 889.0)	(93, 890.0)	(94, 892.0)	(95, 893.0)	(96, 894.0)	(97, 896.0)	(98, 897.0)	(99, 898.0)	(100, 899.0)	(101, 899.0)	(102, 900.0)	(103, 899.0)	(104, 900.0)	(105, 900.0)	(106, 901.0)	(107, 900.0)	(108, 901.0)	(109, 900.0)	(110, 901.0)	(111, 893.0)	(112, 894.0)	(113, 894.0)	(114, 895.0)	(115, 893.0)	(116, 894.0)	(117, 891.0)	(118, 892.0)	(119, 883.0)	(120, 884.0)	(121, 875.0)	(122, 876.0)	(123, 866.0)	(124, 867.0)	(125, 854.0)	(126, 855.0)	(127, 849.0)	(128, 850.0)	(129, 838.0)	(130, 839.0)	(131, 831.0)	(132, 831.0)	(133, 819.0)	(134, 819.0)	(135, 801.0)	(136, 801.0)	(137, 782.0)	(138, 782.0)	(139, 751.0)	(140, 751.0)	(141, 711.0)	(142, 712.0)	(143, 652.0)	(144, 653.0)	(145, 575.0)	(146, 575.0)	(147, 494.0)	(148, 495.0)	(149, 410.0)	(150, 410.0)	(151, 303.0)	(152, 303.0)	(153, 220.0)	(154, 221.0)	(155, 154.0)	(156, 154.0)	(157, 119.0)	(158, 119.0)	(159, 88.0)	(160, 88.0)	(161, 53.0)	(162, 53.0)	(163, 39.0)	(164, 39.0)	(165, 35.0)	(166, 35.0)	(167, 30.0)	(168, 30.0)	(169, 27.0)	(170, 27.0)	(171, 23.0)	(172, 23.0)	(173, 22.0)	(174, 22.0)	(175, 20.0)	(176, 20.0)	(177, 18.0)	(178, 18.0)	(179, 14.0)	(180, 14.0)	(181, 11.0)	(182, 11.0)	(183, 9.0)	(184, 9.0)	(185, 5.0)	

You tell me that I should select the **'best'** projection!
**The population number of nuttalli is 37 and pugetensis is 93.**
Why not select the '37,93' or '36,106' or ……, and select '7,7'(come from you README.md)?

The command line:
./easySFS.py -i wcs_1200.vcf -p wcs_pops.txt -a  -f --proj=7,7

How can you judgment the best projection from the preview result,how to define a standard rule?
Best wishes!

**Comment by isaacovercast** [comment]
Projecting to 7,7 in the README is just an example of the format, it's not meant to be the best value for projection. The dadi manual suggests selecting values of the projection that maximize the number of segregating sites, so this is what i recommend too. There is no _rule_ beyond this, so you have to look at your data and make decisions based on what you see. In general I think if you had to choose, smaller numbers of samples with fewer segregating sites should still give you good results and they'll run faster, so there's somewhat of a trade-off between computational tractability and SFS size. You have to make these decisions for yourself.

**Comment by yuntwang** [comment]
Hi.
@isaacovercast 
I use the easySFS convert VCF to dadi/fastsimcoal style SFS for demographic analysis and find a little question.
In the document of fastsimcoal2:
**“If there are more than two observed samples in the model (say 0, 1, and 2), one would need three separate files with the following suffix（_jointDAFpop1_0.obs, _jointDAFpop2_1.obs, _jointDAFpop2_0.obs."**
But the result of easySFS is  _jointDAFpop0_1.obs, _jointDAFpop1_2.obs, _jointDAFpop0_2.obs.
Can I change the name of SFS file directly.
For example:
Rename _jointDAFpop0_1.obs to _jointDAFpop1_0.obs.
Best wishes!

**Comment by isaacovercast** [comment]
You should be able to just change the name if you like. I _think_ it works
as is, though. Did you try it with they names as output by easySFS?
