### ISSUE TITLE
In the output, what do the 0s and 1s after the frequencies represent?

### ISSUE THREAD

**Issue by mehakmadhura** [isaacovercast/easySFS#50]
Hii!
In the output, one gets some zeros and ones following the frequencies. It would be great if you could clarify what exactly those are.
Thanks

**Comment by isaacovercast** [comment]
Hello,
The zeros and ones are a bitmask to indicate which bins should be considered as data. In an unfolded sfs this whole row of output will be 1s, in a folded sfs the row will contain 0s and 1s in roughly equal proportion, as a result of the folding procedure. Hope that helps.
