### ISSUE TITLE
Analysis appears to run but no output folder or files

### ISSUE THREAD

**Issue by jamesyboy01** [isaacovercast/easySFS#52]

**Comment by isaacovercast** [comment]
Issue text was deleted. It looks like you are running on windows, which i have never tried and am pretty sure won't work, so that could be the problem. hopefully you figured it out.

**Comment by jamesyboy01** [comment]
Hi Isaac. What do you run it on?Regards,James Sent from my iPhoneOn 26 Nov 2022, at 2:43 am, Isaac Overcast ***@***.***> wrote:﻿
Issue text was deleted. It looks like you are running on windows, which i have never tried and am pretty sure won't work, so that could be the problem. hopefully you figured it out.

**Comment by isaacovercast** [comment]
Linux or mac are known to work. If you install Windows Subsystem for Linux this is another way to get it to install and run correctly on a windows machine. Good luck.

**Comment by jamesyboy01** [comment]
Cheers mateSent from my iPhoneOn 26 Nov 2022, at 8:41 am, Isaac Overcast ***@***.***> wrote:﻿
Linux or mac are known to work. If you install Windows Subsystem for Linux this is another way to get it to install and run correctly on a windows machine. Good luck.

**Comment by jamesyboy01** [comment]
Hi Isaac,

I've had another go at running it on Windows and I successfully ran the example files and got the output. My files come up with an error though. It could well be something to do with the file format or something like that, but the error message flashes up to fast for me to read it. Is there a way to recall the error message? Are you able to have a look at my input files (attached) and see if there is something obviously wrong? I'd really appreciate the help.

Regards,
James


________________________________

**Comment by isaacovercast** [comment]
Where did the vcf file that you are using come from? It's possible the vcf is not formatted correctly. How are you running easySFS? What command are you running? You should be able to run the command inside a command line window so you can see the output

**Comment by jamesyboy01** [comment]
I converted a genlite object to vcf in the DartR package. I believe it uses PLINKv1.90 for the conversion. I compared it against your example VCF file and it looks the same to me. I ran easySFS in Anaconda Powershell (Miniconda3).

James

________________________________

**Comment by isaacovercast** [comment]
How big is the vcf file? can you email it? Or wetransfer? It would help if we could see the error message.

**Comment by jamesyboy01** [comment]
Here is the vcf and pop file.
________________________________

**Comment by isaacovercast** [comment]
Email attachments don't get posted to issues, you'll have to go to github and upload the files directly to this issue or else email them to me directly. either way

**Comment by jamesyboy01** [comment]
I just emailed them to you at ***@***.*** Let me know if that's an old email.

Regards,
James
________________________________

**Comment by jamesyboy01** [comment]
Just tried ***@***.*** too.
________________________________
