### ISSUE TITLE
running easySFS on vcf produced by discoSNP

### ISSUE THREAD

**Issue by clorenzo1** [isaacovercast/easySFS#53]
Hi Isaac, 

I have run your easySFS script successfully on a vcf and popmap produced by STACKS software. 

I am trying to run the same script on a vcf and popmap produced by discoSnpRad. My popmap looks like this: 

G1      Tahi_Moana
G2      Tahi_Moana
G3      Tahi_Moana
G4      Tahi_Moana
G5      Tahi_Moana
G6      Tahi_Moana
G7      Tahi_Moana
G8      Mangatolo
G9      Mangatolo
G10     Tui_Malila
G11     Mangatolo
G12     Mangatolo
......

However, when I run it I get the following error: 

   Problem reading populations file. The file should be plain text with one
    individual name and one population name per line, separated by any amount of
    white space. There should be no header line in this file. 
    An example looks like this:
        ind1    pop1
        ind2    pop1
        ind3    pop2
        ind4    pop2
    File you specified is: 
    Error - list index out of range
Traceback (most recent call last):
  File "/path/to/easy_SFS_discoSNP/./test.py", line 677, in <module>
    main()
  File "/path/to/easy_SFS_discoSNP/./test.py", line 616, in main
    ind2pop, pops = get_populations(args.populations,
  File "/path/to/easy_SFS_discoSNP/./test.py", line 476, in get_populations
    pops.setdefault(line.split()[1], [])
IndexError: list index out of range

Do you know why this is? 

Best wishes! 
Coral

**Comment by isaacovercast** [comment]
Hi Coral,
I'm _pretty_ sure there is probably one or more blank lines at the end of the popmap file. I should probably just test for this and ignore it. Check and remove blank lines and try again and let me know how it goes.
-isaac

**Comment by isaacovercast** [comment]
Ok, i tested this and it _is_ because of blank lines in the pops file. I fixed the code so that it ignores blank lines and doesn't crash. ce51033 Thanks for reporting!

**Comment by clorenzo1** [comment]
Isaac, 

Absolutely, thank you so much! Really great software. 

Best 
Coral
