### ISSUE TITLE
Generating pseudoreplicate SFS

### ISSUE THREAD

**Issue by grcvhon** [isaacovercast/easySFS#55]
Hi Isaac,

I do have a question about generating pseudo-replicated SFS. I am trying to generate 100 pseudoreplicated SFS's (resampling with replacement) from the generated observed SFS. I was wondering how could this be achieved in easySFS and if it is possible at all.

I am working with whole genome sequence data (chromosome level) and, for illustration, have generated SFS with following command: `./easySFS.py -i ${in}.vcf -p ${pop_file} -a --proj 18,16,18`. With whole genome sequence data and aligned to chromosome, taking `-a` flag out (i.e. randomly sample 1 SNP per locus or contig) leaves me with the number of chromosomes (which I think makes sense); thus the reason why I included the `-a` flag. Included the `-a`, however, includes all the SNPs from the VCF. I was wondering if there is a way to resample the VCF to generate a pseudo-replicate of the dataset.

Thank you!

PS - thanks for your very helpful responses in the threads here. One was able to answer if I should prune my VCF for LD (such as doing it in plink) before generating SFS via easySFS (https://github.com/isaacovercast/easySFS/issues/22)

**Comment by isaacovercast** [comment]
Hello,

Yes, well the 'best' way to do this would be to randomly sample snps in user configurable windows. I have been meaning to do this for a while but haven't got around to it. Let me look into it and think about how much work it would be.

The other "hackish" way to do this would be to take your VCF file and randomly resample a given number of SNPs from this file, and then run easySFS on each of the sampled VCF files. For example you could use vcftools and the `--thin` argument to sample SNPs separated by a given number of base pairs.

If I can get the windowed thing to work i'll update the ticket.

**Comment by isaacovercast** [comment]
Ok, I added two new flags for easySFS `window_bp` and `window_snp` which sample snps in windows with window sizes specified either in number of snps or in windows of size bp. Can you please check out the code and try this out and let me know how it goes? It will randomly sample one snp within each specified window and should work well for genome data.

**Comment by grcvhon** [comment]
Hi Isaac,

Thank you for your quick response. I tried the new flags and they appear to work. From the output, the flags indeed perform random subsampling (i.e. randomly picking one SNP based on the setting) of the VCF and generates a reduced dataset. 

However, I think my aim (and apologies if I was unclear about this in my query) is to generate a pseudoreplicate SFS with the same amount of information as the observed dataset after sampling with replacement. For example, if there are 10 SNPs from the original dataset (_original.vcf_; using numerals as "SNP" for ease: 0,1,2,3,4,5,6,7,8,9), I would like to generate a pseudoreplicate dataset also with 10 SNPs after sampling with replacement (_pseudo.vcf_; pseudoreplicate: 1,3,4,2,4,0,5,6,7,8). 

Then from that pseudoreplicate, generate a new SFS using easySFS. For example:
Pseudoreplicate: `./easySFS.py -i pseudo.vcf -p ${pop_file} -a --proj 18,16,18`

Thank you!

**Comment by isaacovercast** [comment]
Ahh, ok, I understand. I added a `--resample-vcf` argument (which is hidden in the help menu). This will read in the vcf data and resample snps (with replacement) _before_ sampling snps in windows or one snp per locus/CHROM. Please try that out and let me  know how it works for you.

**Comment by grcvhon** [comment]
Hi Isaac,

Thanks so much. I think that does it! 

To illustrate, here's what I did:

Starting with an original VCF file (=A) which has some 200,000 SNPs, convert to an SFS:
> `./easySFS.py -i ${A}.vcf -p ${pop_file} -a --proj 18,16,18 -o ${test_dir}`
>
> Resulting SFS file has same number of lines in the datadict.txt as the number of SNPs in the VCF

Now, sample the original VCF file (=A) with replacement using `--resample-vcf`:
> `./easySFS.py -i ${A}.vcf -p ${pop_file} -a --resample-vcf --proj 18,16,18 -o ${resamp_dir}`
>
> The datadict.txt of the output resampled SFS file has less number of lines compared to the datadict.txt of the SFS generated from the original VCF.
>
> I am guessing that this reduced number is because some of the SNPs in the original VCF have been replaced/repeated in the resampled VCF, thus changing the output resampled SFS.

Before your update with the `--resample-vcf`, I have found an external approach to perform sampling with replacement. It does the same thing with reduction of lines in datadict.txt after resampling. However, this external approach entails creating a temporary VCF file (= copy of original VCF to work with) then generating X number of resampled VCF files. And then taking those individual resampled VCF files as input into easySFS. 

I think the `--resample-vcf` altogether avoids an extra step or two making it really helpful and convenient!

Many thanks again!

-Vhon

**Comment by isaacovercast** [comment]
Awesome, thanks for the update. The number of snps in the resampled sfs may be different because the downprojection will change this slightly for every resampling. Good luck!

**Comment by grcvhon** [comment]
Right - because the number of samples in the projection and the number of segregating sites at that projection value depends on the input VCF file. And yes, a bit more than slightly from some 200,000 to around 130,000 (lines in the datadict.txt).

**Comment by isaacovercast** [comment]
Ahhh, ok, thank you for checking this. I had not been using unique CHROM/POS for keying the datadict so this is why duplicate snps were getting thrown out (loss of data). I know use a unique key for each snp in the data dict and I can see that --resample-vcf now works correctly and retains the identical number of snps for each replicate. Please test and let me know if you have problems with it.

**Comment by grcvhon** [comment]
Thanks for checking that Isaac! I checked it out and I think it works as intended.

Here's what I did:

Convert original VCF (=A) containing 212,280 SNPs to SFS:
> ` ./easySFS.py -i ${A}.vcf -p ${pop_file} -a --proj 18,16,18 -o ${orig_dir}`
>
> Resulting datadict.txt has 212,280 lines
>
> First few lines of output SFS: 
>> 1 observations. No. of demes and sample sizes are on next line.
>> 3       18 16 18
>> 0 73283 14065 2178 466 79 ...

Resample original VCF (=A) to generate a pseudoreplicate SFS:
> `./easySFS.py -i ${A}.vcf -p ${pop_file} -a --resample-vcf --proj 18,16,18 -o ${pseudo_dir}`
>
> Resulting datadict.txt also has 212,280 lines (same number of SNPs and lines from above i.e., original VCF and original SFS)
>
> I also noticed that the numbers on the first few lines of the output pseudoreplicate SFS are more comparable to the original SFS (i.e., closer in value) compared to previous attempts.
>
>> 1 observations. No. of demes and sample sizes are on next line.
>> 3       18 16 18
>> 0 73133 14392 2187 484 84

I think that with your latest update, the `--resample-vcf` flag correctly generates a pseudoreplicate of the original data.

Many thanks again for updating this very quickly!
