### ISSUE TITLE
(Very minor issue) Wrong paper attached

### ISSUE THREAD

**Issue by forianfinest** [isaacovercast/easySFS#58]
Hello there,
this is not an issue with the software. I just noticed that the reference listed at the end of the description is wrong (it leads me to "Computationally Efficient Composite Likelihood Statistics for Demographic Inference" by Coffman et al. instead of Gutenkunst et al.)
Best wishes,
Mattia

**Comment by isaacovercast** [comment]
Haha, whoops! Thanks, i Fixed it.
-i
