### ISSUE TITLE
pop0 and pop1 notation in fastsimcoal2 outputs 

### ISSUE THREAD

**Issue by bchak10** [isaacovercast/easySFS#59]
Hi, thanks for creating this useful tool! 

In the case of using two populations for inferring a jointSFS, in the fastsimcoal2 output <_jointMAFpop1_0.obs>, I was wondering which population is denoted as pop0 (and associated with the columns d0_0...d0_30) and which population is denoted as pop1 (and associated with the rows d1_0...d1_30)? Is it based on which population appears first in the population assignment file? I happen to have the same number of individuals/haplotypes in the 2 populations so it's not easy to tell. 

In the 1DSFS outputs, both of the populations are denoted as "d0_", might be helpful to code them as d0, d1, d2, etc. respectively.

**Comment by isaacovercast** [comment]
Hello! Thanks for the positive feedback, glad you like it!

Populations are ordered by the order of their first appearance in the pops file. You can also use the `--pop_order` command line argument for easySFS to specify the exact order yourself, if that is what you prefer.

For the 1DSFS the "d0_" headers for the sfs bins are specified by fastsimcoal, so while it's a good idea to use d0, d1, d2 in the 1D files, they would not conform to the required fsc2 format. It's a good idea still.

Let me know if you have any more questions.
-isaac

**Comment by bchak10** [comment]
I see, thanks Isaac!
