### ISSUE TITLE
Monomorphic sites with easySFS from VCF file

### ISSUE THREAD

**Issue by gsgarlata** [isaacovercast/easySFS#61]
Hi Isaac,

First of all, thanks a lot for the easySFS script. It is very useful!
I just wanted to ask a question regarding the number of monomorphic sites recovered in the folded-SFS (for instance a 2D-SFS). I noticed that the user can specify the total length of the sequences used for assembling a VCF file ("--total-length"). However, when I use easySFS without specifying the total length, I still get a significant number of monomorphic sites (which is fine). I just wander from where easySFS gets this number. Does it refer to the non-variant sites included in the VCF (which would not correspond to the total number of monomorphic sites but only to the sites monomorphic for the derived alleles)?

Thank you in advance,
Gabriele

**Comment by isaacovercast** [comment]
Hi Gabriele,

Good observation. The monomorphic sites in the SFS primarily come from the sites that _become_ monomorphic under a given projection level. Think about low-frequency variants. When you project down to a smaller number of samples, the low-frequency variants will sometimes 'become' monomorphic.
Glad you like easySFS!

Hope that helps!
-isaac

PS - I'm going to close this issue, but feel free to email me directly if you have more questions.
