### ISSUE TITLE
Inquiry over projections

### ISSUE THREAD

**Issue by FernandoLeG** [isaacovercast/easySFS#64]
When I ran the preview the projection values go up to two times the number of samples per population. Is this a normal behavior of the software?

The code used was
`./easySFS.py -i RhynchoSFS/sub_ingroup_LU.vcf -p RhynchoSFS/Popsfs1.txt --preview`

this is the output
![Projections](https://github.com/isaacovercast/easySFS/assets/46689465/8ea506b5-cf8a-4898-be3b-21625bf34506)

**Comment by isaacovercast** [comment]
If the organism is diploid then yes this is normal behavior. Haploid samples == 2x diploid samples
