### ISSUE TITLE
killed process in easySFS

### ISSUE THREAD

**Issue by SunJJ230120** [isaacovercast/easySFS#65]
I have a merged vcf file consisting of 5 populations which contained 2774w SNPs. When I run --preview, 64 individuals can produce results, but 129 individuals cannot. I ran this commands : easySFS.py -i sample.vcf.gz -p group.txt -a -f --preview. and I got this error:
/opt/tsce4/torque6/share/cu16/mom_priv/jobs/179113.mu01.SC: line 12:  7823 Killed. 
Anyone know what kind of problem I get? Is there a limit on the number of SNPs in the script?

**Comment by isaacovercast** [comment]
It is not a limit on the number of snps but on the number of individuals * number of populations. The size of the mSFS increases exponentially with each additional population, so more than likely with 5 populatoins and 129 individuals the size of the mSFS is exceeding the available RAM on the computer and it is getting killed. Not much you can do about this except increase RAM, or reduce the number of populations or individuals.

**Comment by SunJJ230120** [comment]
Thanks for the quick reply! 

Good luck,
Stephanie
