### ISSUE TITLE
EasySFS runtime? Running forever?

### ISSUE THREAD

**Issue by lokeyCEU** [isaacovercast/easySFS#66]
Hello,

I am trying to use easySFS to generate SFS for 5 populations to be used as input for dadi and fastsimcoal2.
I run the following;
`vcf=../breeders_noDups_noHighMiss_biallelic_noZ.Jan17-2024.vcf`
`id=breedersVcf_IDindpop.txt`
`nohup ./easySFS.py -i ${vcf} -p ${id} -a -f --preview &`
`nohup ./easySFS.py -i ${vcf} -p ${id} -a -f --proj 48,48,48,48,48 &`

And easySFS starts to run but never finishes. I let it run for over 24 hours and got nothing.
The vcf file is for 241 individuals from 5 populations and has a total size of 56GB with ~9million SNPs.

This shouldn't run more than a couple hours tops right?
Any thoughts?

**Here is the system info**;
`> lscpu`
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  64
  On-line CPU(s) list:   0-63
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) CPU E5-4620 v2 @ 2.60GHz
    CPU family:          6
    Model:               62
    Thread(s) per core:  2
    Core(s) per socket:  8
    Socket(s):           4
    Stepping:            4
    CPU max MHz:         3000.0000
    CPU min MHz:         1200.0000
    BogoMIPS:            5199.96
    
   `> conda info`
     active environment : easySFS
    active env location : /home/mgl7/anaconda3/envs/easySFS
            shell level : 2
       user config file : /home/mgl7/.condarc
 populated config files : /home/mgl7/.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.34=0
                          __linux=5.14.0=0
                          __unix=0=0
       base environment : /home/mgl7/anaconda3  (writable)
      conda av data dir : /home/mgl7/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/mgl7/anaconda3/pkgs
                          /home/mgl7/.conda/pkgs
       envs directories : /home/mgl7/anaconda3/envs
                          /home/mgl7/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Linux/5.14.0-70.13.1.el9_0.x86_64 rocky/9.0 glibc/2.34 aau/0.4.2 
             netrc file : None
           offline mode : False

**Comment by lokeyCEU** [comment]
HI Isaac, thanks for the quick response.

I should have clarified `nohup ./easySFS.py -i ${vcf} -p ${id} -a -f --proj 48,48,48,48,48 &`  is the frozen line I simply gave you all lines for completeness. On that note, `--preview` did finish running in about 1.5 hrs. 

I selected 48 from the preview output. In short, I used the sample sizes and number of segregating sites as a guide but I also wanted to keep a consistent sample size across each population, hence why it's 48 across the board. My actual sample sizes are above 48 for each population.

As to memory usage, the machine I am running has 500Gb and a 9hr old easySFS run is currently using ~270Gb VIRT and RES. I checked in on the memory usage and after about 2 hrs it got to this and stayed there. Usage was obtained via `htop` and `cat /proc/meminfo`.

Thanks for the note about dadi, I am using fastsimcoal which can take large numbers of populations.

**Comment by isaacovercast** [comment]
Hi mitch, thanks for the further details. In the 9hr old easysfs process is
it running at 100% cpu? Sorry if you mentioned this already.

Its 270GB virt and res or each is 270gb? Howuc ram is free on the syatem?

**Comment by lokeyCEU** [comment]
Hi,

Yes ~275 VIRT and RES in htop. CPU% is drifting around 90-100% and MEM% ~50%. Overall memory usage is steady around ~350/503Gb with a couple other processes running as well.

To test if it is a memory issue I subsetted my vcf for half a million sites and it reduced it down to 3Gb. I ran the same command `nohup ./easySFS.py -i ${vcf} -p ${id} -a -f --proj 48,48,48,48,48 &` and it has now been running 20hrs using 20Gb of memory (VIRT & RES) and 100 CPU%.

I also tried it on another machine on our server with the same results.

**Comment by isaacovercast** [comment]
It is weird that --preview would run and finish so quickly and the --proj call would run so long. Can you do me a favor and run the subset vcf again and this time include the `-v` argument? This will print some information about what it is doing and give an idea of where it is getting stuck.

If you want to WeTransfer me a further subset of the sites (~1e5) and the pops file then I can try to take a look myself

**Comment by lokeyCEU** [comment]
Hi Isaac,

I ran things on a set of 100k SNPs and finally got some output and it looks right! Interestingly, the output came out really quickly but the program seems to be running forever. I used the `-v` argument and it didn't output anything into the `nohup.out` file. I replicated this on a separate server as well. So I think the runs with larger SNP sizes were running correctly just taking an expectedly long time. Still don't understand why `-v` wasn't working or why the program doesn't terminate... While I further explore what's going on I'm going to run fastsimcoal with the outputs and see if I get nonsense.

Thanks,
M

**Comment by lokeyCEU** [comment]
Hello,

I upped the vcf to 1e6 snps and it seems to have run completely, produced output, in ~2hrs. But once again the job never terminated. I'm calling it completed because the final snp in `datadict.txt` is the same as the final vcf snp. Furthermore, I have what looks to be the correct output in the `output/` directory.

Given this I'm going to close the issue. Thanks for the program!

I did have an additional comment that may be helpful to other users.
The fastsimcoal2 joint sfs output is named `*jointMAFpop1_0.obs`,  `*jointMAFpop2_0.obs`, etc. but there is no indication which population is p0,p1,etc. and I can't discern it myself because I selected consistent sample sizes across populations (48 for all). I've rerun easySFS with unique sample sizes and discovered that the order of population id's (p0,p1,etc.) is defined by the order in which population IDs are listed in the `-i` input file (sorting the input file does not matter, whichever pop is listed first in the inout file will be p0).

Thanks again,
M

**Comment by isaacovercast** [comment]
Yes, that's right, the order of pops in the fsc2 joint SFS files is determined by the order in the pops file. Thanks for making not of this in case it's useful for someone else in the future. Glad you like easySFS! It's weird that the run never terminates, but i'm glad you got your output files. I will try to figure out why it's not terminating.
