### ISSUE TITLE
Trouble obtaining SFS files

### ISSUE THREAD

**Issue by LeoVincenzi** [isaacovercast/easySFS#67]
Dear developer,
I was trying to perform an SFS analysis on a single VCF composed of 99 samples. All the sample belongs to a single population, so my **population_file.txt** presents 99 rows, each classified as 'pop1'.
Running the preview algorithm, I get a single line with 99 columns: I understand that the following --proj parameter should be set to 99,1. Is it right?
Anyway, running the proj algorithm, I only get the datadict.txt file and empty folders for dadi and fastsimcoal2. 
I guess something is wrong with the projection setting, could be? 

Thanks in advance,
Leo

**Comment by isaacovercast** [comment]
Hi Leo,

If you only have one population then the --proj parameter should only take one value, which would be the number of samples to downproject to. If you run `--proj 99,1` then easySFS will think you have 2 populations (one with 99 samples and one with 1 sample).

When you run --preview, it will show the number of snps retained at a given number of samples for the down projection. You should choose the number of samples based on the results of --preview. Please try running --proj with only one value.

**Comment by isaacovercast** [comment]
Did you see this error message when you ran it with `--proj 99,1`:
```
You must pass in the same number of values for projection as you have populations specified
```

**Comment by LeoVincenzi** [comment]
> Did you see this error message when you ran it with `--proj 99,1`:
> 
> ```
> You must pass in the same number of values for projection as you have populations specified
> ```
 Yes, exactly. 
But now I've tried as you suggested and I got my output:

> output/datadict.txt
> output/dadi:
>           pop1-99.sfs  pop1.sfs
> output/fastsimcoal2:
>           99_MSFS.obs  pop1_MAFpop0.obs

Now, I was wondering which of those files would be the better to plot in order to have a distribution of SFS values.

**Comment by isaacovercast** [comment]
Either of those files will work, the data in the .sfs and .obs files are identical, it's just the format of the file is slightly different to suit dadi/fsc2 expectations.

**Comment by LeoVincenzi** [comment]
Well, the point is that I'm using SFS as quality control on my variant calling, so I'm not interested in performing fsc2 analisys on the population. I was wondering how a file as pop1.sfs can be plotted, considering there are also a lot of zeros.
```

100 folded "pop1"
71919.30312831786 218627.7393177001 223489.007026734 115309.0938625433 81901.75007191818 62731.1017334846 50540.74788960171 42037.18206913465 35746.60530788105 31025.70107321083 27368.44260202931 24439.65321962513 22015.78892980013 19958.5647893225 18236.94849098672 16728.82989252914 15409.6573604606 14261.39669893422 13279.37168115423 12421.05854220952 11684.19296061132 11065.14971632931 10547.50766011142 10147.46245962358 9851.848081602182 9667.407569003732 9577.872716474769 9569.785314539784 9640.018494339864 9755.531861666139 9906.914242879862 10076.58027676374 10244.70816738068 10410.52861487058 10571.91427518562 10726.0666504739 10892.33030312534 11085.77678312653 11306.29554085073 11560.20764822663 11825.34632788905 12085.46837805426 12323.9346695248 12521.77446719697 12678.02783535393 12790.11098440488 12867.21037209807 12919.02923318779 12949.65393512709 12966.40077234971 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

```

Also, I don't understand what those values represent in the two rows.

**Comment by isaacovercast** [comment]
The 1d sfs has 3 lines:
- Information about the sfs (number of samples, folded condition, and pop id)
- The sfs data (monomorphics, singletons, doubletons, etc)
- A bitmask indicating whether to include or exclude each bin (which if you are not doing fsc2 can be safely ignored).

In python you can plot the data like this (a very standard bar plot representation of the sfs):
```
data = np.array([float(x) for x in "71919.30312831786 218627.7393177001 223489.007026734 115309.0938625433 81901.75007191818 62731.1017334846 50540.74788960171 42037.18206913465 35746.60530788105 31025.70107321083 27368.44260202931 24439.65321962513 22015.78892980013 19958.5647893225 18236.94849098672 16728.82989252914 15409.6573604606 14261.39669893422 13279.37168115423 12421.05854220952 11684.19296061132 11065.14971632931 10547.50766011142 10147.46245962358 9851.848081602182 9667.407569003732 9577.872716474769 9569.785314539784 9640.018494339864 9755.531861666139 9906.914242879862 10076.58027676374 10244.70816738068 10410.52861487058 10571.91427518562 10726.0666504739 10892.33030312534 11085.77678312653 11306.29554085073 11560.20764822663 11825.34632788905 12085.46837805426 12323.9346695248 12521.77446719697 12678.02783535393 12790.11098440488 12867.21037209807 12919.02923318779 12949.65393512709 12966.40077234971 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0".split()])
plt.bar(range(len(data)), data)
```

The trailing zeros in the line of data are the result of the folding procedure, where you don't have information about the ancestral state so major and minor allele frequencies are indistinguishable. You can ignore these zeros in a folded sfs.

Hope that helps.

**Comment by LeoVincenzi** [comment]
Thank you very much @isaacovercast, it helps a lot in understanding! I will try as you suggest!
