### ISSUE TITLE
Very low projection value

### ISSUE THREAD

**Issue by ModiShrushti** [isaacovercast/easySFS#68]
Thanks for easySFS. I am trying to determine the sequence length for my GADMA run using easySFS but it seems that I am getting very low values from the folded as well as unfolded SFS vector output.
1.079365079365078 1.365079365079354 3.301587301587281 5.571428571428532 11.82539682539675 8.523809523809511 8.518518518518508 4.899470899470878 4.582010582010571 1.92857142857142 2.404761904761901 0.6190476190476117 2.029100529100506 2.148148148148156 1.997354497354492 0.5661375661375609 1.304232804232792 1.097883597883589 0.7407407407407365 0.4232804232804208 0.07407407407407368 0.669312169312168 1.764550264550249 0.5343915343915295 0.03174603174603155 0 0
1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1.

Is this normal?

**Comment by isaacovercast** [comment]
Those look very low indeed (unusable). What are the results from running
--preview mode? How many snps in the input vcf?
-isaac

**Comment by isaacovercast** [comment]
How many snps are in your input vcf? The number of segregating sites is
very low across all projection values, so it seems there are few snps in
the vcf. Is that right?

**Comment by ModiShrushti** [comment]
There are more than sufficient 
SNPs n = 5656507.

**Comment by isaacovercast** [comment]
5.6 million variable site? You should see way more segregating sites in
--preview mode. Something is going on that i dont understand.  Can u
wetransfer me the vcf and the pops file? I can take a look

**Comment by ModiShrushti** [comment]
Yes sure! Thanks for your help. Should I use your github mail?

**Comment by isaacovercast** [comment]
If the vcf is large wetransfer is better. U can email the pops file

**Comment by ModiShrushti** [comment]
I have sent it to you.

**Comment by isaacovercast** [comment]
The default behavior of easySFS is to retain "one SNP per locus" on the assumption that the data is RADSeq-like. If the data is WGS then the default behavior will select 1 SNP per CHROM, which will drastically reduce the size of the data. For WGS data you can use one of the following strategies:

```
  --window-bp WINDOW_BP
                        Select SNPs based on window size in base pairs
  --window-snp WINDOW_SNP
                        Select SNPs based on window size in number of SNPs
  -a                  Keep all snps within each RAD locus (ie. do _not_ randomly sample 1 snp per locus).
```
