### ISSUE TITLE
Confirmation required in case of sample differences between vcf and popfile

### ISSUE THREAD

**Issue by r-poloni** [isaacovercast/easySFS#69]
HI, I was trying to run easySFS on a vcf with populations represented by different number of samples. To avoid an over-representation in the vcf, I reduced the number of samples in the more abundant populations through passing a popfile.txt with fewer samples:

`easySFS.py -i vcf_file.vcf.gz -p popfile.txt --preview`

If this is run through a bash script, it throws this error:
`
Continue, excluding samples not in both pops file and VCF? (yes/no)
Traceback (most recent call last):
  File "/scratch/rpoloni/env/easySFS/easySFS/easySFS.py", line 802, in <module>
    main()
  File "/scratch/rpoloni/env/easySFS/easySFS/easySFS.py", line 722, in main
    ind2pop, indnames, pops = check_inputs(ind2pop, indnames, pops)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/rpoloni/env/easySFS/easySFS/easySFS.py", line 514, in check_inputs
    cont = input("\nContinue, excluding samples not in both pops file and VCF? (yes/no)\n")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line`

I tried to use it in interactive mode with a small subset of the vcf, and it works. However, processing a large vcf while connecting to a node and in interactive node is. not really handy, and even if the issue can be overcome with subsetting the vcf with another program , I think it is useful to report this. The installation has been done following what is the suggested procedure in the readme of the program.

**Comment by isaacovercast** [comment]
Hello, did you try using 'expect' to automate the interaction?

https://www.geeksforgeeks.org/expect-command-in-linux-with-examples/

Let me know if that works.

**Comment by r-poloni** [comment]
Hi @isaacovercast! Thank you for the suggestion. Unfortunately I am working in a cluster, so I cannot install expect. I still can run it in interactive mode, so no big deal. However, maybe you could add an option --exclude-samples in the next update? I think it could be useful.

**Comment by isaacovercast** [comment]
I added a `-y` flag to continue without prompting if samples differ between pops and vcf files.

5cf3d9f..2e21aff

Let me know if you have problems with it if you get a chance to try it.

**Comment by r-poloni** [comment]
@isaacovercast thank you very much! It works perfectly.
