### ISSUE TITLE
what does the ‘sample sizes’ represent？

### ISSUE THREAD

**Issue by PingpingHA** [isaacovercast/easySFS#7]
I'm a little confused about the ‘sample sizes’ in --proj flag.  That doesn't mean the real number of individuals in populations (if I keep all samples)?
And I noticed that the maximum ‘sample sizes’ in the column given by  --preview flag  equals to （2*individuals-1）.   Is that because diploid species ?  and what does the ‘sample sizes’ represent in --proj flag ?

**Comment by isaacovercast** [comment]
Hello. Yes, you got it right, sample size is counted as haploid, so 2 diploid individuals will turn to maximum 4 haploid sample size for the --proj flag.
